fli-iam/shanoir-ng

shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/InitialStartupState.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/LoginPanelActionListener.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/StartupStateContext.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/State.java, shanoir-uploader/src/main/java/org/shanoir/uploader/cryptography/BlowfishAlgorithm.java, shanoir-uploader/src/main/java/org/shanoir/uploader/gui/MainWindow.java, shanoir-uploader/src/main/java/org/shanoir/uploader/utils/Encryption.java, shanoir-uploader/src/main/java/org/shanoir/uploader/utils/Util.java, shanoir-uploader/src/main/resources/general.properties
Pseudonymus removed from our code repository. Executables will have to be put manually now.
=> ShanoirUploader v6.0 - pseudonymus externalised

shanoir-uploader/src/main/java/org/shanoir/uploader/upload/UploadServiceJob.java
to avoid sync problems on the server when auto-import starts and files
are still being copied in the backend.
=> Important bug fix: add upload-job.xml guaranteed always as the last file

.gitignore, shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/InitialStartupState.java, shanoir-uploader/src/main/java/org/shanoir/uploader/gui/AboutWindow.java, shanoir-uploader/src/main/resources/general.properties, shanoir-uploader/src/main/resources/log4j.properties, shanoir-uploader/src/main/resources/messages_en.properties, shanoir-uploader/src/main/resources/messages_fr.properties, shanoir-uploader/src/main/resources/shanoir_server.properties
- pseudonymus key integrated back into .jar, as required by OFSEP
- .su folder extended with version number
- bug correct in shanoir_server.properties "ServiceService"
- version number equal now in AboutWindow/Help
=> Commit of version v6.0.1

shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
=> WADO-URI download implemented for download of datasets in sh-old,

shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/protocol/MrProtocolStrategy.java
=> Appning -> Reverse changes, keep usefull null check

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
- Init massiveDownload API
- Check that the connected user has the given right for at least one of the given dataset list
- Remove from the datasetIds list the ids the not found datasetIds and the not allowed datasetIds
=> massive download back-end init

shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpenerNG.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListenerNG.java, shanoir-uploader/src/main/java/org/shanoir/uploader/gui/CurrentUploadsWindowTable.java, shanoir-uploader/src/main/java/org/shanoir/uploader/nominativeData/CurrentNominativeDataController.java, shanoir-uploader/src/main/resources/messages_en.properties, shanoir-uploader/src/main/resources/messages_fr.properties
done - profiles ng: hide investigator in GUI
done - ShUp: common name > 2 chars, same for subject identifier
done - Feature request Ofsep: delete error imports to clean up
=> ShUp: minor bug fixes + impl of feature request Ofsep

shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts
=> Little bugfix: update study allowed changing file + clinical mandatory

docker-compose/migration_scripts/Neurinfo/4_datasets_migration.py
tested: runs now without error and scores are displayed correctly within exam.
=> Migration scripts: fixes for clinical scores

shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpener.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpenerNG.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListenerNG.java, shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/StudyCard.java
Fixes
- OFSEP bug in prod: manufacturer missing in infos from Pacs: NPE
- GitHub Issue #207 ShUp: migration to NG (REST): add studycard compatibility #207
=> 2 fixes: missing manufacturer from pacs + GitHub Issue #207 fixed

shanoir-uploader/src/main/resources/log4j.properties, shanoir-uploader/src/main/resources/profile.Neurinfo-NG-qualif/keycloak.json, shanoir-uploader/src/main/resources/profile.Neurinfo-NG/keycloak.json, shanoir-uploader/src/main/resources/profile.OFSEP-NG-qualif/keycloak.json, shanoir-uploader/src/main/resources/profile.OFSEP-NG/keycloak.json
and configured and fix for logging introduced, to overload config from sh-ws.jar
=> ShUp: new NG profiles: missing keycloak.jsons added

docker-compose/migration_scripts/Neurinfo/1_users_migration.py, docker-compose/migration_scripts/Neurinfo/2_studies_migration.py, docker-compose/migration_scripts/Neurinfo/3_import_migration.py, docker-compose/migration_scripts/Neurinfo/4_datasets_migration.py
a few fixes needed for running the migration on the qualif instance
please review carefully (especially the removal of the subqueries)
=> Migration fixes

docker-compose/migration_scripts/Neurinfo/4_datasets_migration.py
- Python language errors corrected: indentation + elif
- unknown column studycard_rule_id corrected
- corrected: missing assignments, modified in memory, but not injected into db
- missing rule_id in assignments added, to solve missing link problem with rules
=> Missing migration script part for StudyCards, overtaken from Julien

docker-compose/migration_scripts/Neurinfo/4_datasets_migration.py, docker-compose/migration_scripts/Neurinfo/dbutils.py
did two optimisations to improve migration times
- use bulk inserts (for the bigger tables) to improve the througput
- import DATASET_FILE and PACS_DATASET_FILE in a single pass
With these changes the whole migration takes 37 minutes (instead of 4~5 hours)
=> Migration speedup

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApi.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java, shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/subjectstudy/controler/SubjectStudyApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subjectstudy/service/SubjectStudyService.java, shanoir-ng-studies/src/test/java/org/shanoir/ng/study/SubjectStudyApiSecurityTest.java
The import / view datasets should now work for a USER/EXPERT
=> Import fixes

docker-compose/keycloak/entrypoint
(for migration purpose or in case the realm config is updated)
=> support import/export of the shanoir-ng realm

.env, docker-compose.yml, docker-compose/nginx/entrypoint, utils/entrypoint_common
This is a crude hack. Maybe you will have a better idea to implement it.
=> add SHANOIR_COLORS to allow overriding the main css colors

shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/service/StudyCardProcessingService.java
See #373
It's a quickfix. A better solution will be to understand why some OLD assignments don't work here.
=> Quickfix for import with studycards

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListenerNG.java, shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/Examination.java, shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/importer/ImportJob.java
Bug fix for GitHub issue #415
ShUp: with qualif (sh-ng): exam creation: access denied #415
Reason: model on server has removed IdName from ExaminationDTO
=> ShUp Testing with shanoir-qualif (sh-ng):

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectService.java, shanoir-ng-studies/src/main/resources/application.yml, shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/SubjectServiceSecurityTest.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpenerNG.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListenerNG.java
ShUp: with qualif (sh-ng): errors with imports #417
MS Studies: prepared for external debugging, profile dev in Spring Boot
ShUp: feature: select already existing exam, when from the same study
In detail:
- ms studies: updateSubject, rights changed to same as saveNewSubject (in layer controller + service)
- minor code format modifications
=> Final fixes for GitHub Issue #417

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/DatasetAcquisitionDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/DatasetAcquisitionDecorator.java, shanoir-ng-front/src/app/dataset-acquisitions/shared/dataset-acquisition.dto.ts
@Nunien I think using DatasetAcquisitionDTO, you did not propagate all the protocol part to the front. I added something in the mapper, but it may not be ideal.
There is another problem displaying the protocol: I think the protocol is not transferred in an adapted angular object.
=> Shanoir issue#409 Dataset Acq protocol display [Do not merge]

shanoir-ng-front/src/app/solr/solr.search.component.ts
- Remove dates from saved filters
=> #450 Solr => Date filter does not work.

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java, shanoir-ng-front/src/app/dataset-acquisitions/shared/dataset-acquisition.service.ts, shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
=> fix several empty list bug messages

shanoir-ng-front/src/app/solr/solr.search.component.ts
Allow white spaces in solr queries
=> Shanoir issue#451 => Solr query with space

shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/Subject.java
- Ignore non existing JSON properties
=> SHanoir-Issue#430 - Export as BIDS

shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
- When no study available for an user, respond with 204.
=> Shanoir issue#456 => no study => error messazge in solr search

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
The method used by Yao returned a list of datasets and not a boolean => Change the method to do the check properly.
=> Shanoir issue#487 - download nifti as simple user

docker-compose/migration_scripts/Neurinfo/4_datasets_migration.py
=> Fix for echo_time, flip_angle, inversion_time, repetition_time

shanoir-ng-front/src/app/app.component.html, shanoir-ng-front/src/app/app.module.ts, shanoir-ng-front/src/app/async-tasks/async-tasks.component.ts, shanoir-ng-front/src/app/datasets/shared/dataset.service.ts, shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts, shanoir-ng-front/src/app/http-interceptor/http-interceptor.ts, shanoir-ng-front/src/app/import/select-series/select-series.component.css, shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts, shanoir-ng-front/src/app/shared/components/tree/tree-node.component.css, shanoir-ng-front/src/app/shared/loader/loader.component.css, shanoir-ng-front/src/app/shared/loader/loader.component.html, shanoir-ng-front/src/app/shared/loader/loader.component.ts, shanoir-ng-front/src/app/shared/loader/loader.service.ts, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.css, shanoir-ng-front/src/assets/css/common.css
The loader shows every time a http request is pending
=> Fix tasks columns + add a global loader

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
=> Shanoir issue#550 download data

shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/SolrRepositoryImpl.java
Shanoir-issue#531 Correct solr search logic
- Better wildcard management
- Use _str fields for better results also
=> Shanoir issue#531 Solr search logic

bootstrap.sh
=> fix the bootstrap script

docker-compose.yml
Dockerhub updated not to use debugger (root dependant) anymore.
=> Shanoir issue#563 Correct dicomifier

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
- Actually check the extra data file path difference to delete files
=> Shanoir-issue#554 Delete extra data files from the disk

shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/CustomHostnameVerifier.java, shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/HttpService.java
https://github.com/fli-iam/shanoir-ng/issues/582
=> Bug fix for GitHub issue: ShUp: certificate issue #582

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
Change download name for single datasets:
- dataset ID + dataset name + series description (if existing)
=> Shanoir issue#557 Download name

shanoir-uploader/READ_ME.txt, shanoir-uploader/downloadDataset.bat, shanoir-uploader/downloadDataset.sh, shanoir-uploader/pom.xml, shanoir-uploader/src/main/java/org/shanoir/downloader/ShanoirDownloader.java, shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java, shanoir-uploader/start-shup-linux-mac-java.sh, shanoir-uploader/start-shup-windows-java.bat
finishes issue: 
ShanoirUploader: downloadDataset.sh not working (probably same for .bat)
#520
=> ShUp updated to v7.0.1, Downloader: fix introduced for cert issue SNI.

shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/SolrRepositoryImpl.java, shanoir-ng-front/src/app/shared/checkbox-list/checkbox-list.component.html, shanoir-ng-front/src/app/shared/checkbox-list/checkbox-list.component.ts
- Add a search bar to solr search to sort facets by name
- Do no limit facets
=> Shanoir issue#569 Solr search => facet limit & search bar

shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListenerNG.java
https://github.com/fli-iam/shanoir-ng/issues/603
=> Bug fix for GitHub issue: #603

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java, shanoir-ng-import/src/test/java/org/shanoir/ng/importer/ImporterApiControllerTest.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/bruker/BrukerApiController.java
- Clean after bruker import
- Clean .download files (not possible for .zip)
- Clean after dicom import
- Clean regularly /tmp folder based on last update & name
=> Shanoir-issue#601 Clean temporary folder

shanoir-ng-front/src/app/app.routing.ts, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.ts, shanoir-ng-front/src/app/users/user/user.component.html, shanoir-ng-front/src/app/users/user/user.component.ts
- Allow simple user to edit its own profile from side menu
=> Shanoir issue#592 Access to user profile

shanoir-ng-front/src/app/acquisition-equipments/manufacturer-model/manufacturer-model.component.html
Correcting a JS error => using formControlName.
Also, database has to be updated (how ?)
=> Shanoir issue#590 create manufacturer (model)

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/repository/ExaminationRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceSecurityTest.java
=> Shanoir issue#536 load preclinical examination only as expert

shanoir-uploader/src/main/java/org/shanoir/downloader/ShanoirDownloader.java, shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpOnloadConfig.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/AuthenticationConfigurationState.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/LoginPanelActionListener.java, shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/HttpService.java, shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClientNG.java
ShUp: login with KeycloakInstalled.loginDesktop not working #615
https://github.com/fli-iam/shanoir-ng/issues/615
In interaction with Keycloak, if KeycloakInstalled.loginDesktop using the system browser, does not work
and throw an exception ConnectException a manual login is proposed inside ShUp, that directly calls Keycloak
using the offline access call to ask for a token.
- Refactoring done with Downloader: keycloakLogin integrated into ClientNG and gained a lot of lines
=> - Bug fix for GitHub issue: #615

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RabbitMQStudiesService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQUserService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java, shanoir-ng-users/src/main/resources/templates/notifyStudyAdminDataImported.html
- Better logs
- Only get users that have "receive import email" role (and not admin)
- Better message content
=> Shanoir issue#611 receive import mail

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RabbitMQStudiesService.java, shanoir-ng-studies/src/test/java/org/shanoir/ng/study/service/RabbitMQStudiesServiceTest.java
- Use user_id instead of study_user id
- Use newImport and not anonymization
- Add tests to check all this..
=> Shanoir issue#611 receive email for import

shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts
- Edit users rights in study => set to boolean
- Only download when in "view"
=> Shanoir-issue#607 Study edit problems

shanoir-ng-front/src/app/shared/side-menu/side-menu.component.css, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html, shanoir-ng-front/src/app/users/user/user.component.html
improve profile feature : css + see role, etc
=> improve profile feature : css + see role, etc

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-front/src/app/datasets/dataset/dataset.component.html, shanoir-ng-front/src/app/datasets/dataset/dataset.component.ts, shanoir-ng-front/src/app/shared/components/papaya/papaya.component.html
- Download DICOM only (change download name with date)
- Do not load nifti everytime => Only on demand
- Exception management
=> Shanoir-issue#617 Nitfi file in dicom

shanoir-ng-front/src/app/examinations/examination/examination.component.html, shanoir-ng-front/src/app/shared/date-picker/date-picker.component.ts
- During import, when exam date is set, user cannot change it anymore
=> Shanoir-issue#625 do no update exam date on import

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
- Remove the expected return as "zip" to avoid unexpected error
=> Shanoir-issue#648 Expected 403 when got unauthorized

shanoir-ng-front/src/app/subjects/subject/subject.component.html, shanoir-ng-studies/src/main/java/org/shanoir/ng/bids/service/StudyBIDSService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/bids/service/StudyBIDSServiceImpl.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java, shanoir-ng-studies/src/test/java/org/shanoir/ng/study/service/StudyBIDSServiceImplTest.java, shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/service/SubjectServiceTest.java
Cannot update subject name anymore (front + back)
Remove BIDS update as it was based on name change only
=> Shanoir issue#628 dissallow subject name update

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/exporter/controller/BidsApiController.java, shanoir-ng-front/src/app/datasets/download/dataset-download.component.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
- Better rights management on examination, study, datasets APIs
- Remove double download button
- Set mime type
- default download to nii
=> Shanoir issue#647 Download management

shanoir-ng-front/src/app/acquisition-equipments/manufacturer-model/manufacturer-model.component.html, shanoir-ng-front/src/app/examinations/examination/examination.component.html, shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.html, shanoir-ng-front/src/app/import/eeg-clinical-context/eeg-clinical-context.component.html, shanoir-ng-front/src/app/preclinical/anesthetics/anesthetic/edit/anesthetic-form.component.html, shanoir-ng-front/src/app/shared/select/select.component.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts, shanoir-ng-front/src/app/study-cards/study-card-rules/action/action.component.html, shanoir-ng-front/src/app/study-cards/study-card/study-card.component.html, shanoir-ng-front/src/app/subjects/tree/reverse-subject-node.component.ts, shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts
I don't know exactly why but it seems that using "change" for an output in a controelValueAccessor is not a good idea. An event was, in some cases, overriding ours.
Also I corrected the form validation so the update button is correctly enabled/disabled when the center field changes.
=> fixs bugs with select box and study edit see #643

shanoir-ng-users/pom.xml, shanoir-ng-users/src/main/java/org/shanoir/ng/scheduling/ScheduledTasks.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/repository/UserRepository.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java, shanoir-ng-users/src/test/java/org/shanoir/ng/scheduling/ScheduledTasksTest.java
- In scheduledTasks, add expiration user propagation to KC-
- Add tests
=> Shanoir-issue#660 Propagate disable user to keycloak

docker-compose/migration_scripts/OFSEP/2_studies_migration.py
case-sensitive in prod env for rel_subject_study.
=> Fix for OFSEP migration script

shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.ts, shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts, shanoir-ng-front/src/app/studies/tree/reverse-study-node.component.ts, shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts, shanoir-ng-front/src/app/tree/tree.model.ts
- Add sortingIndex and order by sorting index
=> Shanoir-issue#534 Order datasetAcquisition in studytree

shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/ImportJob.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/service/ImporterServiceTest.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/ImportJob.java
- Catch error from async method
- Better display error
- Do not display serie sequence but description
=> Shanoir-issue#687 Import error message management

shanoir-ng-front/src/app/app.routing.ts
- Update routing to be able to create a exam/subject as user
I actually had a local pb, my import => study_user database was empty..
=> Shanoir-issue#698 Create preclinical subject as user

shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.html, shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.ts
=> make subject type mandatory

docker-compose/nginx/entrypoint
Reverts fli-iam/shanoir-ng#735
=> Revert "Fix app.css styles in entrypoint"

docker-compose/nginx/entrypoint
Reverts fli-iam/shanoir-ng#736
=> Revert "Revert "Fix app.css styles in entrypoint""

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
- Add subject name to dicom datasets
- Add "index" to nifti datasets
=> Shanoir issue#722 #723 Download datasets name

shanoir-ng-preclinical/src/main/java/org/shanoir/ng/configuration/ShanoirPreclinicalConfiguration.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/bruker/BrukerApiController.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/extra_data/ExtraDataApiController.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/pathologies/pathology_models/PathologyModelApiController.java, shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/bruker/BrukerApiControllerTest.java, shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/examination_extradata/ExtraDataApiControllerTest.java, shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/pathologies/pathology_models/PathologyModelApiControllerTest.java
- Use @values instead of @Configuration to force in test
- Use temporary folder in tests
=> Shanoir-issue#656 Useless file created while launching preclinical tests

shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQUserService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java, shanoir-ng-users/src/main/resources/templates/notifyStudyAdminDataImported.html, shanoir-ng-users/src/test/java/org/shanoir/ng/email/EmailServiceTest.java
- Also send series description in email (use event messages)
=> Shanoir-issue#658 Admin import email template

shanoir-ng-front/src/app/app-routing.module.ts
=> Shanoir-issue#689 Edit Examination rights

docker-compose.yml, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/exporter/service/BIDSServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/ImportJob.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/CtDatasetStrategy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/MrDatasetStrategy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/PetDatasetStragegy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/CtDatasetAcquisitionStrategy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/MrDatasetAcquisitionStrategy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/PetDatasetAcquisitionStrategy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetexpression/NiftiDatasetExpressionStrategy.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
- Name file just after the conversion to avoid same name
- Use Encoder/decoder to get files with specific names
- Change download name
=> Shanoir issue#759  Dicomifier nifti converter management

docker-compose.yml, shanoir-ng-front/src/app/preclinical/examination/shared/animal-examination.service.ts
- Update dicomifier reference for bruker conversion
- Allow examination creation by expert (use examination DTO)
Excuse me @michaelkain if I had tested the bruker import yesterday instead of trying to solve 'rabbitmq' problem in the tests I would have seen the problem :(
I Updated dicomifier to use the proper command, and tested both dicom2bruker and dicom2nifti.
=> Shanoir-issue#804 #800 Bruker import

shanoir-ng-datasets/src/main/resources/application.yml, shanoir-ng-datasets/src/test/java/org/shanoir/ng/TestConfiguration.java, shanoir-ng-import/src/main/resources/application.yml, shanoir-ng-preclinical/src/main/resources/application.yml, shanoir-ng-studies/src/main/resources/application.yml, shanoir-ng-studies/src/test/java/org/shanoir/ng/TestConfiguration.java, shanoir-ng-users/src/main/resources/application.yml, shanoir-ng-users/src/test/java/org/shanoir/ng/TestConfiguration.java
- Deactivate rabbitMQ for tests
- Force RabbitTemplate mock
=> Shanoir-issue#803 Correct rabbitmq error in tests

shanoir-ng-users/src/main/java/org/shanoir/ng/accountrequest/controller/AccountRequestApiController.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/controller/UserApiController.java, shanoir-ng-users/src/test/java/org/shanoir/ng/accountrequest/AccountRequestApiControllerTest.java, shanoir-ng-users/src/test/java/org/shanoir/ng/user/UserApiControllerTest.java
- Move challenge subscription to account acceptation
@michaelkain I corrected it directly, so it's done
=> Shanoir-issue#825 Account request challenge

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
Fix for NPE: [Challenge] ShUp import not working after changes (qualif) #829
Not a fix for the overall issue, BUT I could not reproduce it on my dev machine
=> Fix to avoid NPE

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RabbitMQStudiesService.java
Update RabbitMQStudiesService.java
=> Fix for DUA, challenger account request: auto-put into study

docker-compose/keycloak/cfg/shanoir-ng-realm.json
https://github.com/fli-iam/shanoir-ng/issues/829
=> Update shanoir-ng-realm.json: fixes ShUp issue #829

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/ExaminationDatasetAcquisitionDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/SimpleDatasetAcquisitionDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/dto/ExaminationDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/dto/SubjectExaminationDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/dto/mapper/ExaminationDecorator.java, shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts
linked to  https://github.com/fli-iam/shanoir-ng/issues/776
=> extra data in study tree

shanoir-uploader/pom.xml, shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpOnloadConfig.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/AuthenticationConfigurationState.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/AuthenticationManualConfigurationState.java, shanoir-uploader/src/main/java/org/shanoir/uploader/gui/ShUpStartupDialog.java, shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClientNG.java
=> KeycloakInstalled removed + own token refresh added

shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.ts
- Base DICOM/select check on serial number only first, then name to
avoid misleading error messages
=> Shanoir-issue#621 import warning on center/acquisition equipement

shanoir-ng-front/package.json, shanoir-ng-front/src/app/app.component.css, shanoir-ng-front/src/app/app.component.html, shanoir-ng-front/src/app/coils/coil/coil.component.html, shanoir-ng-front/src/app/coils/coil/coil.component.ts, shanoir-ng-front/src/app/import/import.component.ts, shanoir-ng-front/src/app/shared/side-menu/dev.css, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.css, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.ts, shanoir-ng-front/src/assets/css/common.css
* instance colors system is improved
* can now display an instance name
* an admin profile has a colored tag "administrator"
* the menu states (open/close) is saved over a browser session
=> instance colors + admin highlight

docker-compose/import/Dockerfile, shanoir-ng-front/src/app/study-cards/study-card/study-card.component.html, shanoir-ng-front/src/app/study-cards/study-card/study-card.component.ts
- Update dcm2niix version
- Set dcm2niix as default + tooltip
=> Shanoir-issue#876 Update and use dcm2niix by default

shanoir-ng-front/src/app/import/select-series/select-series.component.ts, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
Reverts fli-iam/shanoir-ng#899
=> Revert "test"

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/DatasetAndProcessingsDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/DatasetAndProcessingsDTOInterface.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/mapper/DatasetMapper.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/EegDatasetAndProcessingsDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/MrDatasetAndProcessingsDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java
see https://github.com/fli-iam/shanoir-ng/issues/874
=> Shanoir issue 874 - sliceThinckness in getDatasetById

shanoir-uploader/downloadDataset.bat, shanoir-uploader/src/main/java/org/shanoir/downloader/ShanoirDownloader.java, shanoir-uploader/src/main/java/org/shanoir/uploader/gui/DownloaderPanel.java, shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClientNG.java
long formating in GUI, launch from command line on windows, force exit when download finished, better handle connection error.
=> fix shanoir downloader issues

shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java, shanoir-ng-users/src/main/resources/templates/notifyStudyAdminDataImported.html
When importing data on a study:
Import email should use "< a href >" and exam date should be on a single line.
=> Shanoir-issue#930 Update import email

db-changes/datasets/01062021_dataset_acquisition_import_date.sql
@Nunien I re-opened this pull request as one DB change was missing.
Jean-Côme
=> shanoir-issue#937 add magnetic_field_strength to DB

shanoir-ng-front/src/app/app.module.ts, shanoir-ng-front/src/app/home/challenge/challenge-block.component.css, shanoir-ng-front/src/app/home/challenge/challenge-block.component.html, shanoir-ng-front/src/app/home/challenge/challenge-block.component.ts, shanoir-ng-front/src/app/home/home.component.css, shanoir-ng-front/src/app/home/home.component.html, shanoir-ng-front/src/app/home/home.component.ts
=> multiple challenges in home

bootstrap.sh, docker-compose.yml
- bootstrap.sh: start with or without Keycloak
- docker-compose.yml: depends_on to Keycloak removed from sh-ng microservices
=> bootstrap.sh: --no-keycloak + --no-dcm4chee flag

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/AcquisitionContrast.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
- Do not filter spectro data
- Better manage unknown contrastAgent
=> Shanoir-issue#969 Include spectro data

shanoir-ng-front/src/app/async-tasks/async-tasks.component.ts, shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
What to test:
- No more "pipe broken" exception in users logs.
- You can now click on the import job message to go directly to the examination.
=> Shanoir-issue#938 direct link from job to examination

shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
=> Shanoir-issue#922 Solr tag : Get all subject study

docker-compose/database/3_add_statistics_procedure.sql, docker-compose/database/db-changes/datasets/0011_3_add_statistics_procedure.sql
update statistics procedure to export dates
=> update statistics procedure to export dates

shanoir-ng-front/src/app/preclinical/animalSubject/edit/animalSubject-form.component.html, shanoir-ng-front/src/app/preclinical/pathologies/subjectPathology/list/subjectPathology-list.component.ts, shanoir-ng-front/src/app/preclinical/shared/subjectEntity-list-input.abstract.ts, shanoir-ng-front/src/app/preclinical/therapies/subjectTherapy/list/subjectTherapy-list.component.ts
What to test:
- Create a new preclinical subject
- Add a new therapy / pathology
--> The therapy / pathology is well displayed in the table.
Test create, delete, update.
Closes #1076
=> Shanoir-issue#1076 Display correctly animal therapies / pathologies

shanoir-ng-front/src/app/app.module.ts, shanoir-ng-front/src/app/async-tasks/async-tasks.component.ts, shanoir-ng-front/src/app/shared/components/entity/entity-list.browser.component.abstract.ts, shanoir-ng-front/src/app/shared/components/loading-bar/loading-bar.component.css, shanoir-ng-front/src/app/shared/components/loading-bar/loading-bar.component.html, shanoir-ng-front/src/app/shared/components/loading-bar/loading-bar.component.ts, shanoir-ng-front/src/app/shared/components/table/table.component.css, shanoir-ng-front/src/app/shared/components/table/table.component.html, shanoir-ng-front/src/app/shared/components/table/table.component.ts, shanoir-ng-front/src/app/shared/notifications/notifications.service.ts, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.ts, shanoir-ng-front/src/app/studies/study-list/study-list.component.ts, shanoir-ng-front/src/app/users/user/user.component.ts, shanoir-ng-front/src/app/utils/ng-var.directive.ts
* check that the front doesn't make unnecessary tasks api calls
=> Tasks table auto refresh

shanoir-ng-datasets/src/main/resources/scripts/import.sql, shanoir-ng-studies/src/main/resources/scripts/import.sql
How to test:
- Deploy from scratch (or set the argument to 'true' in application.yml for each microservice) and check the logic.
ddl-auto: create
Closes #1087
=> Shanoir-issue#1087 Simplify SQL scripts

docker-compose/database/3_add_statistics_procedure.sql, docker-compose/database/db-changes/datasets/0011_3_add_statistics_procedure.sql, docker-compose/database/db-changes/datasets/0012_3_add_statistics_procedure.sql
Fix export statistics procedure: the column headers for the import, creation and examination dates were missing.
=> Statistics

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
Request from Elise: When downloading dicom, include dataset name + exam date to be able to order them correctly.
Closes #1102
=> shanoir-issue#1102 Download DCM - Use exam date + serieDescription

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RabbitMQStudiesService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java
How to test:
- Add a new user to a challenge
- Accept this user with admin
An email is sent to the study administrator (that has the "new member email" option to true) when the account request is accepted.
Closes #1109
=> Shanoir-issue#1109 Study member update for challenge

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java, shanoir-ng-users/src/main/resources/templates/notifyUserAddedToStudy.html
A mail is now sent:
- To study administrator
- To every added user
When updating a study - adding a new user
Closes #1127
=> Shanoir-issue#1127 Send user mail when added to study

docker-compose/datasets/Dockerfile, docker-compose/import/Dockerfile
Allow download of datasets with accents.
Closes #1147
=> Shanoir-issue#1147 Allow download of datasets with accents.

shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/repository/SubjectRepository.java
=> Shanoir-issue#1171 Get subject name by center code -> only numerical

shanoir-ng-front/src/app/import/eeg-upload/eeg-upload.component.html, shanoir-ng-front/src/app/import/eeg-upload/eeg-upload.component.ts, shanoir-ng-front/src/app/import/shared/import.service.ts
How to test:
- Import from EEG an important archive and check the upload progress bar is working properly.
=> shanoir-issue#970 progress bar for import upload - EEG

shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
Processed dataset is now working.
Closes #1159
=> Shanoir-issue#1159 processed dataset bug

shanoir-ng-front/src/app/preclinical/animalSubject/edit/animalSubject-form.component.html, shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts, shanoir-ng-front/src/app/shared/components/subject-study-list/subject-study-list.component.html, shanoir-ng-front/src/app/shared/components/subject-study-list/subject-study-list.component.ts, shanoir-ng-front/src/app/shared/select/select.component.ts, shanoir-ng-front/src/app/solr/solr.search.component.css, shanoir-ng-front/src/app/studies/study/study.component.css, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts, shanoir-ng-front/src/app/subjects/subject/subject.component.html, shanoir-ng-front/src/assets/css/common.css
* add tabs in study page
* tree tabs are disabled in edit/create mode
* add a view mode to the subject-study list
=> add tabs in study

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/BidsImporterService.java, shanoir-ng-front/src/app/import/bids/bids-upload.component.html, shanoir-ng-front/src/app/import/bids/bids-upload.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/acquisitionequipment/service/RabbitMqCenterService.java
- Equipment description
- Auto-select center
- Reset rabbitMQ reply timeout
=> Shanoir issue#1187 Bids import - complement

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
How to test:
- Create a dataset with a '/' in its name
- Try to download this dataset
-> Should not fail anymore
=> shanoir-issue#1234 download dataset with '/' name

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
Dataset 316887 failing in production -> dataset comment is used in folder path (and not file name)
Closes #1234
=> shanoir-issue#1234 dataset download comment contains '/' bug

shanoir-ng-front/src/app/datasets/download/dataset-download.component.html, shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts, shanoir-ng-front/src/app/shared/components/form-footer/form-footer.component.html, shanoir-ng-front/src/app/shared/components/table/search/search.component.html, shanoir-ng-front/src/app/shared/components/table/table.component.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts
See https://github.com/fli-iam/shanoir-ng/issues/1212
=> fix user getall bug in study

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/StudyInstanceUIDHandler.java, shanoir-ng-front/src/app/examinations/examination/examination.component.ts
I tested with examIds from 1 to 16.000.000, so it should be fine now
=> Fix for GitHub issue #1261 Ohif viewer higher 9 issue

shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts, shanoir-ng-front/src/app/subjects/subject-list/subject-list.component.ts
resolves https://github.com/fli-iam/shanoir-ng/issues/1263
=> add add button in subjects and examinations

shanoir-ng-users/src/main/java/org/shanoir/ng/accountrequest/controller/AccountRequestApiController.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/controller/UserApiController.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/model/User.java
=> fix error when creating user

shanoir-ng-front/src/app/coils/coil/coil.component.ts
=> fix : Create manufacturer model during coil creation

shanoir-ng-front/src/app/datasets/download/dataset-download.component.html
Closes #1287
How to test:
- go to study tree
- select multiples datasets
- Select box appears correctly (you can select either nifti or dicom)
=> shanoir-issue#1287 correct dataset download selected datasets

shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/SolrRepositoryCustom.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/SolrRepositoryImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
fix https://github.com/fli-iam/shanoir-ng/issues/1293
=> Solr security fix

shanoir-ng-datasets/src/main/java/org/shanoir/ng/bids/BidsDeserializer.java
Closes #1299
How to test:
- Create a new study
- Create a new subject associated to this study but with no data
- Go to study detail and open BIDS tree
- -> Should be working now.
=> shanoir-issue#1299 Bids deserializer when empty folder

shanoir-ng-front/src/app/preclinical/pathologies/pathologyModel/edit/pathologyModel-form.component.html
Closes #1295
How to test
- Go to preclinical model
- Edit one
- Click on Cancel button
=> shanoir-issue#1295 cancel button for pathology model edit

shanoir-ng-front/src/app/preclinical/anesthetics/anesthetic/edit/anesthetic-form.component.ts, shanoir-ng-front/src/app/preclinical/pathologies/pathologyModel/edit/pathologyModel-form.component.html
Closes #1297 
How to test:
- Create a new anesthetic
- Add two ingredients
- Remove one of the two ingredients
- Save the anesthetic
--> There is no more 2 ingredients saved.
=> Shanoir issue#1297 Anesthetic creation - ingredient deletion 

shanoir-ng-front/src/app/study-cards/study-card/study-card.component.html, shanoir-ng-front/src/app/study-cards/study-card/study-card.component.ts
studycard creation now display a clear msg if a studycard name is taken
=> unique name error display

shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts
How to reproduce:
- As an expert, be part of a study with no rights to admin this study.
- Got to examination list
- -> an error is triggered then it comes back when displaying the list of examinations
Closes #1336
=> shanoir-issue#1336 examination list canDelete display

shanoir-ng-import/src/main/java/org/shanoir/ng/utils/ImportUtils.java
Closes #1341 
This error happens when a zip file is not zipped an appropriate way.
> only DEFLATED entries can have EXT descriptor
[test.zip](https://github.com/fli-iam/shanoir-ng/files/8897532/test.zip)
See test.zip for tests.
=> shanoir-issue#1341 use ZipFile instead of zipInputStream -> 

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/RabbitMqExaminationService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/ImportJob.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/BidsImporterService.java, shanoir-ng-front/src/app/import/shared/dicom-data.model.ts, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/bids/BidsImporterApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/ImportJob.java, shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/importer/ImportJob.java
- Get rid of x-user-event when not necessary
- Transmit information as string otherwise
=> shanoir-issue#1268 Import mail - wrong user_id/name in mail

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApi.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/carmin/GetPathResponse.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/carmin/OneOfGetPathResponse.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/carmin/Path.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/carmin/TypeEnum.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/carmin/UploadData.java
This pull request is to integrate upload endpoint in MS-import, so that VIP can upload the results to the tmp folder using the path from URI.
=> upload endpoint to the tmp folder 

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/CtDataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/ImageFlavor.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/MrDataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/CoilType.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/CtDatasetStrategy.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/MrDatasetStrategy.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/coil/model/CoilType.java
CoilType.VOLUME introduced to avoid exception during import
ImageFlavor introduced and extension on MrDatasetStrategy
=> DICOM Enhanced, next extension

shanoir-ng-datasets/pom.xml, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/configuration/AsyncConfig.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/controller/CarminDatasetProcessingApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/model/Execution.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitor.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitorService.java, shanoir-ng-datasets/src/main/resources/application.yml
This pull request contains the cron job to check VIP server if the execution is finished to update the execution status, after that it creates a ProcessedDataset to finish the cycle
=> execution cron task

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
How to reproduce the bug : search birth date = 19811003 on qualif
=> pacs import multi study fix

shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.css, shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.html, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
How to test:
- Realize an import with CT dicom
- Select dicomifier as a nifti converter (check the warning is present)
-  The import should not fail.
Closes #1339
=> shanoir-issue#1339 dicomifier bug when deleting inexisting file

shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html, shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.html
Closes #1385 
How to test:
- Go to dataset detail -> Direct link to examination
- Go to acquisition detail -> Direct link to exmamination
=> shanoir-issue#1385 Add direct link to examination in dataset/acq

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/dto/ExaminationDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/mapper/SubjectDecorator.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/mapper/SubjectMapper.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/model/SubjectDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/model/SubjectStudyDTO.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiSecurityTest.java, shanoir-ng-front/src/app/examinations/shared/examination.dto.ts, shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.ts
@julien-louis It is normally good, if you can check it ?
thanks !
Jean-Côme
=> shanoir-study-center-limit - Update exam/subject DTO

shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.html, shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.ts
@julien-louis some corrections
=> shanoit-limit-center - correct front

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/dto/ExaminationDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
Closes #1418 
Make an import from shanoir-uploader
Create a new examination
-> The exammination-subject link is correct.
=> shanoir-issue#1418 Exam-subject for shanoir uploader bug

shanoir-ng-front/src/app/shared/components/subject-study-list/subject-study-list.component.ts
Closes #1433 
How to test?
- Open a Study detail
- Go to subjects tab
- Click on a subject -> Wrong subject opens (Id of reference = subjectStudy id instead of subject id)
=> shanoir-issue#1433-subject-study-detail-use subject id, not subjectstudy

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
Closes #1438 
How to test:
- Connect as an admin
- Update an examination
- Change subject
--> Subject is now well updated.
=> shanoir-issue#1438-examination-update - allow subject update on exam

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java, shanoir-ng-datasets/src/main/resources/application.yml
MS Datasets for DicomWeb interface, introduces ConnectionPoolManager for httpClient that calls the PACS.
=> Possible performance fix ohif-viewer

shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFromCsvRunner.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/query/Patient.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/query/Study.java
How to test:
- Import from pacs with a CSV. In date column, change the pattern to yyy-MM-dd-HH and check that the hour of aqcuisition is in taken into account.
Closes #1432
=> Shanoir issue#1432 uploader date filter

shanoir-ng-front/src/app/shared/utils/handle-error.service.ts
How to reproduce:
- Connect and get to a study with more than 50 datasets
- download all datasets
- Check the error message -> should be adapted
Closes #1453
=> shanoir-issue#1453 dataset download error

shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitor.java
this PR contains adding multiple result extension support while importing the result.
And the possibility to import results from subdirectories from the result tar file.
=> Adding multiple result extension support 

shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/controller/CarminDatasetProcessingApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/controller/CarminDatasetProcessingApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitor.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitorService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/utils/KeycloakServiceAccountUtils.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/utils/KeycloakServiceClientUtils.java, shanoir-ng-datasets/src/main/resources/application.yml
This PR contains the use of keycloak service account to communicate with VIP-API.
It contains also the fix of a thread variable conflict.
=> Adding keycloak service Account

docker-compose/keycloak/entrypoint, utils/oneshot
- exit as soon as the final pattern is matched (instead of hanging if any pattern is not matched)
- check additional messages in keycloak init/import/export logs
=> improve the oneshot script

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
- Do not download dicom for processed datasets
- Download nifti correctly
How to test:
- Import a processed dataset
- On solr search, select the processed dataset and a MR dataset
- Download as nifti -> Both are downloaded
- Download as dicom -> Only the MR is downloaded
=> #1515 download processing download

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/repository/SubjectRepository.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java
Filter subject page by study.
Closes #1492
=> #1492 Subject Page filter

shanoir-ng-front/src/app/subjects/subject-list/subject-list.component.ts
Subject list - list loading as expert has a problem
=> #1492 subject list loading

shanoir-ng-users/src/main/java/org/shanoir/ng/user/controller/UserApi.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/controller/UserApiController.java
Closes #1539
How to test:
- Update a user to change it expiration date
- Make an extension request with this user
- Accept or refuse this extension request -> it now works.
=> #1539 extension request - re-allow extension request and account request

shanoir-ng-front/src/app/solr/solr.search.component.ts, shanoir-ng-front/src/app/solr/text-search/solr.text-search-mode.component.html, shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/dateTime/DateTimeUtils.java, shanoir-ng-studies/src/main/resources/scripts/import.sql
Closes #1513 
How to test:
- Import data on qualif
- Check using F12 that your new data examination date is like 00:00:00.000Z
- Make na expert research with:
examinationDate:[2016-04-27T00:00:00Z TO 2016-04-28T00:00:00Z] Nothing returned (=issue)
With adapted date so that the the first date is the date of the examination.
It should appear
=> Shanoir issue#1513 solr dates

shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java
=> #1544 add username and motivation

shanoir-uploader/src/test/java/org/shanoir/uploader/test/datasets/dicom/web/StowDicomSRTest.java, shanoir-uploader/src/test/java/org/shanoir/uploader/test/importer/ZipFileImportTest.java
=> #1568 Repare build by ignoring the problem

shanoir-ng-front/src/app/studies/studyuser/studyuser-list.component.html, shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java, shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestServiceImpl.java, shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/repository/AccessRequestRepository.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/model/User.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java, shanoir-ng-users/src/test/java/org/shanoir/ng/accessrequest/AccessRequestApiControllerTest.java, shanoir-ng-users/src/test/java/org/shanoir/ng/user/UserServiceTest.java, shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClient.java
3 things to test:
1) Create a new user with an access request on a study
Refuse this access request -> the user is well deleted
2) Create a new user with an access request on a study
Directly delete this user -> The user is well deleted
3) From study detail, add a user from username instead of email
=> #1544 Delete user with access request + Search by username

shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java
Create a new user on a public study -> email is sent to study admin now
=> #1544 access request - send email to study admin - new user

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/InputDTO.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/utils/DatasetFileUtils.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiSecurityTest.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/utils/DatasetFileUtilsTest.java, shanoir-ng-datasets/src/test/resources/input.json, shanoir-ng-front/src/app/datasets/shared/dataset.service.ts, shanoir-ng-front/src/app/examinations/examination/examination.component.ts
- implement a new export by examination id in dataset microservice
- generate input.json as specified
- integrate input.json to the new examination export when format is dicom
=> #1280 step 1

shanoir-ng-front/src/app/welcome/welcome.component.css, shanoir-ng-front/src/app/welcome/welcome.component.html, shanoir-ng-front/src/app/welcome/welcome.component.ts
I tried to improve a bit the welcome page.
=> welcome page css

shanoir-ng-front/src/app/solr/solr.document.model.ts, shanoir-ng-front/src/app/solr/solr.service.ts, shanoir-ng-front/src/app/studies/study/study.component.ts
fix bugs stated by malo : in solr, selected datasets could not be individually removed
=> fix bugs with solr selection

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
=> #1620 download naming

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/repository/ExaminationRepositoryImpl.java
fix https://github.com/fli-iam/shanoir-ng/issues/1626
=> fix exam list studyId bug

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
Correct bug on getSizeByStudyId
Ko if not admin
=> [fli-iam#248] Correct bug on method security

shanoir-ng-front/src/app/preclinical/animalSubject/edit/animalSubject-form.component.ts
- Correctly display an error when creating a subject with an already taken name.
Closes #1624 
How to test:
- Import bruker
- Try to create a subject with an already existing subject name
- -> = An error is displayed and no subject is created
=> #1624 - bruker import subject bug

shanoir-ng-front/src/app/processing/pipelines/pipelines.component.ts
@youennmerel I remade the correction, it was my fear.
@julien-louis can you merge it please ? Thanks !
=> #1517 - multi dataset pipeline - bugfix

shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitor.java, shanoir-ng-front/src/app/processing/pipelines/pipelines.component.ts, shanoir-ng-ms-common/src/main/java/org/shanoir/ng/utils/KeycloakUtil.java
- Retrieve only access token
- Better acces token management
@youennmerel You may try this one
=> #1517 - multiple dataset processing

shanoir-ng-front/src/app/shared/components/subject-study-list/subject-study-list.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subjectstudy/repository/SubjectStudyRepository.java, shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/service/SubjectServiceTest.java
Closes #1302
@julien-louis I re-created it properly.
How to test:
- Add data on a study on a new subject -> delete this subject from study -> clear warning -> if deleted, all subject and associated data are deleted.
- If the subject is in 2 different studis -> not deleted.
=> Shanoir issue#1302 2 orphan subject

docker-compose/keycloak/themes/shanoir-theme/login/login-update-password.ftl, shanoir-ng-front/src/app/users/user/user.component.html, shanoir-ng-front/src/app/users/user/user.component.ts, shanoir-ng-front/src/assets/css/login.css
Logged in users can now update their password from the profile page with the "update password" button
=> Shanoir issue#1593: change password

shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/VIPUserService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/VIPUserServiceImpl.java, shanoir-ng-users/src/main/resources/application.yml
- Disable VIP by default
- Do not block user creation when failing to create VIP user
How to test:
1) disable VIP
- Make a new account request
- user is well created
2) Enable VIP
- Make a new account request
- User is well created
- An error message is in the logs
=> #1665 user creation request bug

shanoir-ng-front/src/app/users/access-request/access-request.component.html
- Remove buttons from access request detail
Closes #1667 
How to test:
- Connect as user
- Request an access on a public study
- Buttons Accept / Decline do not appear anymore
=> #1667 access request buttons

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java, shanoir-ng-front/src/app/studies/shared/study.service.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
Added :
- `studies.data_user_agreement_file`
- `studies.protocol_file_path`
- `datasets.extra_data_file_path` 
To the storage volume sum.
@julien-louis As discussed with you, I'd be happy to have your 2 cents on the storage volume refresh when uploading new file. Thx !
=> [fli-iam#248-2] add extra files to total size

shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment-list/acquisition-equipment-list.component.ts, shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment/acquisition-equipment.component.ts, shanoir-ng-front/src/app/acquisition-equipments/shared/acquisition-equipment.service.ts, shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts, shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts, shanoir-ng-front/src/app/shared/models/error.model.ts, shanoir-ng-front/src/app/study-cards/shared/study-card.service.ts
When deleting equipment from list or details, precheck if a study card is linked to the entity and abort deletion.
=> [fli-iam#1688] Check if linked study card before deleting equipment

shanoir-ng-front/src/app/processing/execution/execution.component.html, shanoir-ng-front/src/app/processing/execution/execution.component.ts
When creating a new pipeline execution, the field "Execution name" must be filled with a default value :
If modified, all characters that are not letters, numbers, `_` or `-` must be replaced by `_` in VIP call (see browser console).
=> [fli-iam#1662] Add default pipeline execution name

shanoir-ng-front/src/app/app-routing.module.ts, shanoir-ng-front/src/app/shared/components/table/table.component.html, shanoir-ng-front/src/app/studies/study-list/study-list.component.ts, shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.css, shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.ts
https://github.com/fli-iam/shanoir-ng/issues/1619
=> Locks in studies

shanoir-ng-front/src/app/app-routing.module.ts, shanoir-ng-front/src/app/shared/components/table/table.component.html, shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.css, shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.ts
fix https://github.com/fli-iam/shanoir-ng/issues/1673
\+ small bugs
=> fix study card reapply bug

docker-compose/datasets/Dockerfile, docker-compose/import/Dockerfile, docker-compose/preclinical/Dockerfile, docker-compose/studies/Dockerfile, docker-compose/users/Dockerfile
fix https://github.com/fli-iam/shanoir-ng/issues/1277 
looks to be working fine
=> from debian stretch to bullseye

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/Study.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/BidsImporterService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/EegImporterService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/service/ImporterServiceTest.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/SerieToDatasetsSeparator.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Study.java
- better GUI messages via Events to the user for the imports
- clean up production log for better visibility in ms import
=> [fli-iam#1702] Add more precises messages in import job

shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition-list/dataset-acquisition-list.component.ts, shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts
fix https://github.com/fli-iam/shanoir-ng/issues/1607
=> Column sort bugs

shanoir-ng-front/src/app/centers/shared/center.dto.ts, shanoir-ng-front/src/app/studies/shared/study.dto.ts
=> shanoir-issue#1728-2: when building studycenter object from studycenterDTO, also keep prefixes

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
- Avoid unavoidable NPE
How to test:
- Ask me for some multi-examination datasets
- Realize an import with such data (Import -> Dicom -> check multi-examination)
-> The file loads correctly and then import goes on and does not fail.
Closes #1738
=> #1738 - multi-exam-import bug

shanoir-ng-front/src/app/shared/components/table/table.component.html
=> shanoir-issue#1744: onRowClick event on table is back

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrSequenceVariant.java
- Add unknown variant
Closes #1746 
How to test:
- Ask youenn for the weird data
- Import it
- No more error
=> shanoir-issue#1746-import-missing-MrSequenceVariant

docker-compose/keycloak/cfg/shanoir-ng-realm.json, docker-compose/keycloak/entrypoint, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/output/DefaultOutputProcessing.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitor.java, shanoir-ng-datasets/src/main/resources/application.yml, shanoir-ng-front/src/app/async-tasks/async-tasks.component.ts, shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.html, shanoir-ng-front/src/app/processing/pipelines/pipeline/pipeline.component.html, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApi.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApiController.java
- Configure service-account on keycloak
- Multiple-datasets processing with ct-tiqua pipeline
- Visualize VIP execution as a job in shanoir jobs list
=> [fli-iam#1280] Add service-account client on keycloak conf

shanoir-ng-front/src/app/app.module.ts, shanoir-ng-front/src/app/solr/solr.search.component.ts
new solr button : copy selected ids to clipboard
=> new solr button : copy selected ids to clipboard

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/resources/scripts/test-data-h2.sql, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetDownloaderServiceTest.java
New datasets are now downloadable
=> Shanoir issue#1602 Security hot fix

shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/field/DatasetAcquisitionMetadataField.java
=> Fix quality control bugs

shanoir-ng-front/src/app/carmin/shared/carmin-client.service.ts, shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.html, shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts
Download stdout & stderr logs as files from a VIP processing
=> [fli-iam#1724] get execution stdout & stderr from processing

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Patient.java, shanoir-uploader/pom.xml, shanoir-uploader/src/main/java/org/shanoir/uploader/action/DownloadOrCopyRunnable.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/FindDicomActionListener.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListener.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFromCsvRunner.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/DicomServerClient.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/query/SerieTreeNode.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/query/StudyTreeNode.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/retrieve/DcmRcvManager.java, shanoir-uploader/src/main/java/org/shanoir/uploader/upload/UploadServiceJob.java
- Fix for StaticLoggerBinder error, cleans up logger configuration
- Fix: same series info display as before
- Sort series by seriesNumber in tree view
- Fix for ignored series are displayed in tree for selection
=> Refactor on ShUp: final steps + fixes

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java, shanoir-uploader/src/main/java/org/shanoir/uploader/action/DicomServerConfigurationListener.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/DicomServerClient.java, shanoir-uploader/src/main/java/org/shanoir/uploader/gui/DicomServerConfigurationWindow.java
this PR fixes, that the DICOM echo is back operational in ShUp after the huge refactor
=> ShUp: all from ms-import + ms-import now c-echo-scu

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java, shanoir-ng-import/src/test/java/org/shanoir/ng/importer/ImporterApiControllerTest.java, shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
How to test:
- Get some EEG data (ask me if necessary)
- Import EEG data, the "Import now" step should now be working well.
=> #1829-EEG-import-bug - Use rabbitMQ

shanoir-ng-front/src/app/import/dicom-upload/dicom-upload.component.ts, shanoir-ng-front/src/app/import/shared/import.service.ts, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApi.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
- Allow default equipment ID when not in dicom
How to test:
- Ask me for the data
- Upload to multi exam import
- Import finishes
=> #1843 - multi exam import bug

shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
Cannot launch multiple quality runs, concurrent exception
=> fix rest template concurrent exception

shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/bruker/BrukerApiController.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/extra_data/ExtraDataApiController.java, shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/examination_extradata/ExtraDataApiControllerTest.java
Unit test `ExtraDataApiControllerTest.uploadExtraDataTest` is failiing on github CI but OK on local env.
```
Error:  Failures: 
Error:    ExtraDataApiControllerTest.uploadExtraDataTest:173 Status expected:<200> but was:<422>
[INFO] 
Error:  Tests run: 197, Failures: 1, Errors: 0, Skipped: 0
```
=> Correct failing unit test in preclinical

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html, shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.ts, shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.html, shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.ts, shanoir-ng-front/src/app/datasets/shared/dataset.service.ts, shanoir-ng-front/src/app/examinations/examination/examination.component.html, shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts, shanoir-ng-front/src/app/import/bids/bids-upload.component.html
Add the possibility to download datasets from an acquisition
How to test :
- Download BIDS, DICOM, NIfTI, EEG from acquisition details
- Download BIDS, DICOM, NIfTI, EEG from acquisition node
=> [Fli iam#1812] Download from a dataset acquisition

shanoir-ng-datasets/src/main/java/org/shanoir/ng/bids/service/BIDSServiceImpl.java
Corrected:
- dataset file naming with subject name / id
- EEG dataset file naming
Closes #1878 
How to test:
- Import MR dataset
- Import EEG dataset
--> The dataset file naming respect (more or less, but subject name / index) the BIDS structure.
https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetic-resonance-imaging-data.html
=> #1878 Bids compliance

shanoir-ng-front/src/app/import/dicom-upload/dicom-upload.component.html
=> #1853 multi exam import

shanoir-ng-front/src/app/import/dicom-upload/dicom-upload.component.html
=> #1856 multi exam import

docker-compose/import/Dockerfile
How to test:
- Import data use mriconverter converter (CT is better)
closes #1903
=> #1902-openjdk-removal

shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts, shanoir-ng-front/src/app/solr/solr.search.component.ts
How to test:
- Try to download from solr on a study you don't have the download right
- Download from firefox
- Dataset folder is now in a new folder with timestamp.
=> #1920 download browser corrections

shanoir-ng-front/src/app/solr/solr.search.component.ts
@pierrehenri-dauvergne corrected the problem !
=> #1920 - download rights over multiple pages

shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
How to test:
- Import multi-frame dicoms
- re download it -> it comes all together
=> #1950-multi frame download

shanoir-ng-front/src/app/shared/components/table/table.component.ts
Date values in table are in mm-dd-yyyy format instead of dd-mm-yyyy (in entity details)
How to test:
check if the value in examination details is the same as in solr
=> shanoir-issue#1947: fix date format in tables

shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
- Extract correctly dicom files after PACS download
How to test:
- Download dicom and open them
=> #1958-multipart-download-bug

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/DicomProcessing.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
See comment from michael here: https://github.com/fli-iam/shanoir-ng/pull/1998/files
=> Shanoir hotfix missing sop uid

shanoir-ng-front/src/app/shared/components/table/table.component.ts
fix https://github.com/fli-iam/shanoir-ng/issues/1987
=> fix date format in jobs

shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts, shanoir-ng-front/src/app/study-cards/study-card-rules/study-card-rules.component.ts
https://github.com/fli-iam/shanoir-ng/issues/1991
* When creating / editing a study, asterisks for mandatory fields were disappearing when switching tabs.The pr fixes it.
* The pr adds asterisks to tabs that contain mandatory fields
=> asterisk in study

shanoir-ng-front/src/app/studies/studyuser/studyuser-list.component.html, shanoir-ng-front/src/app/studies/studyuser/studyuser-list.component.ts
fix https://github.com/fli-iam/shanoir-ng/issues/1828
=> disabled can_see_all checkbox for current user

shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-datasets/src/main/resources/application.yml, shanoir-ng-import/src/main/resources/application.yml, shanoir-ng-users/src/main/resources/application.yml
Primus performance - augment connection pool to adapt for performance (and PRIMUS)
=> #2046 - connection pool performance

shanoir-ng-front/src/app/studies/shared/study.service.ts, shanoir-ng-front/src/app/studies/study-list/study-list.component.ts
single queue + cache for volume storage requests
=> Storage volume requests optimization

shanoir-ng-front/src/app/shared/components/table/browser-paging.model.ts, shanoir-ng-front/src/app/shared/components/table/table.component.ts
Fix dates in examination-list and dataset-acquisition-list
How to test:
Open "examination list" page in shanoir
Check the Date column, it says "03/04/2019"
Open this examination-details, it says "04/03/2019"
This is fixed now
=> cherry-pick from JL PR #2015 - fix dates again

shanoir-ng-front/src/app/preclinical/pathologies/pathologyModel/edit/pathologyModel-form.component.html, shanoir-ng-front/src/app/preclinical/pathologies/pathologyModel/edit/pathologyModel-form.component.ts, shanoir-ng-front/src/app/preclinical/therapies/therapy/edit/therapy-form.component.html, shanoir-ng-front/src/app/preclinical/therapies/therapy/edit/therapy-form.component.ts, shanoir-uploader/pom.xml
How to test:
As an expert
Go to 'pathology models'
Create a new pathology model with an already existing name
The form should display a message saying 'Name should be unique'
Do the same with therapies
=> shanoir-issue#966: add user feedback

.github/dependabot.yml
Hi @jcomedouteau,
I was missing one space in the yml config file, and chaos ensued :clown_face:
=> Correct dependabot config file

docker-compose/database/db-changes/preclinical/0002_anesthetic-type_as_enum.sql, shanoir-ng-front/src/app/import/pre-clinical-context/pre-clinical-context.component.ts, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/anesthetics/anesthetic/AnestheticType.java
How to test:
- the preclinical MS starts and works
=> Bugfix - preclinical spring boot - update column

docker-compose/database/db-changes/preclinical/0003_injection_interval_as_enum.sql, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/references/InjectionInterval.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/references/InjectionSite.java, shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/references/InjectionType.java
=> #bugfix preclinical microservice

docker-compose/database/4_add_studyStatistics_procedure.sql, docker-compose/database/db-changes/studies/0018_add_studyStatistics_procedure.sql, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyStatisticsDTO.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/repository/StudyRepositoryImpl.java
adding center_prefix as set by user from table studies.study_center in the getStudyStatistic procedure.
=> add center_prefix column to get study statistic procedure

shanoir-ng-front/src/app/examinations/examination/examination.component.html, shanoir-ng-front/src/app/examinations/examination/examination.component.ts, shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts, shanoir-ng-front/src/app/studies/study/study.component.ts
Fix #2030 and #2023
When updating a study or an examination, the user can upload large files, click on "update" and download said file, which would cause an error because the upload is not finished.
How to test :
Open a study, go to "Files" tab (or Open an examination for #2030)
Edit and upload a large file
Click update
Try to download the file
=> Shanoir issue#2023 and #2030: download file is available before making sure the upload is done

shanoir-ng-front/src/app/shared/components/table/pager/pager.component.html, shanoir-ng-front/src/app/shared/components/table/table.component.css, shanoir-ng-front/src/app/shared/components/table/table.component.html, shanoir-ng-front/src/app/shared/components/table/table.component.ts
Under each table, new feature to jump to a specific page number: 
How to test:
Enter a number and hit 'enter' on your keyboard
=> shanoir-issue#2096: add a 'jump to page' feature

shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
How to test:
-Find a dataset with a dataset file as WADO URI (containing /instances/) and anothter without.
- Download both datasets
- Both datasets can be downloaded
Closes #2128
=> #2128 download from pacs fails

shanoir-ng-front/src/app/studies/study-list/study-list.component.ts
Fix #2078 
How to test:
Create a new user
Login with it
Open the study list
Before: an error was thrown
Now: no error
=> shanoir-issue#2078: add a check if user isnt part on any study

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrScanningSequence.java
unfortunately I could not reproduce the problem even with the import of a modified dicom containing S
=> add S to ScanningSequence

shanoir-ng-front/src/app/study-cards/study-card/study-card.component.ts
=> correct develop

shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts
This PR just adds the examination.comment column to examination-list page
=> shanoir-issue#2175: add examination.comment to examination-list

docker-compose-dev.yml, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/repository/ExaminationRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/repository/ExaminationRepositoryCustom.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/repository/ExaminationRepositoryImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/SecurityService.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dicom/web/DICOMJsonApiControllerTest.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiSecurityTest.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceSecurityTest.java, shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.html, shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts, shanoir-ng-front/src/app/examinations/shared/examination.service.ts, shanoir-ng-front/src/app/preclinical/examination/list/animal-examination-list.component.ts, shanoir-ng-front/src/app/shared/components/table/search/search.component.html
Added this search field in examination list:
How to test:
For each field (*, id, subject, comment, examination date, research study and center), make sure the research is not taking too long and that it's returning the correct results
=> shanoir-issue#2204: allow research in examination list

shanoir-ng-front/src/app/import/clinical-context/clinical-context.abstract.component.ts
How to test:
Create a study with two centers
For this study, create a study card for each center (one acquisition equipment per center is needed)
In the member tab, remove the rights for one center:
My study cards list:
Import MR data, in the clinical context, you should only see the studycard for the center you have the right:
=> shanoir-issue#2214: filters studycards by centers on which the user has rights in import form

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
Hot to test:
- Download nifti with reconversion
- Check that /tmp/userId folder inside microservice is well emptied
=> #2219 clean after nifti reconversion

docker-compose/database/db-changes/studies/0020_set_default_studycardpolicy.sql, shanoir-ng-front/src/app/studies/shared/study.dto.ts, shanoir-ng-front/src/app/studies/shared/study.model.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyDTO.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/model/Study.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/model/StudyCardPolicy.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
How to test:
Create or update a study
Change the value of "study card policy"
Check in database that it was stored
This PR only adds a new field, it is not used yet.
This PR also fixes https://github.com/fli-iam/shanoir-ng/issues/2103
=> shanoir-issue#2199: add studycard policy to study details + save in database

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
Closes #2233 
How to test:
- Import a processed dataset (using interface or execution)
--> Processed dataset is correctly created
=> 2233-processed-dataset-creation - Avoid NPE while creating processed dataset

shanoir-ng-studies/src/main/java/org/shanoir/ng/ShanoirStudiesApplication.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/acquisitionequipment/controler/AcquisitionEquipmentApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/acquisitionequipment/controler/AcquisitionEquipmentApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/center/controler/CenterApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/center/controler/CenterApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/coil/controler/CoilApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/coil/controler/CoilApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/security/BearerAuth.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/security/OAuth2Auth.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/manufacturermodel/controler/ManufacturerApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/manufacturermodel/controler/ManufacturerModelApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/shared/common/CommonApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subjectstudy/controler/SubjectStudyApi.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/subjectstudy/controler/SubjectStudyApiController.java, shanoir-ng-studies/src/main/resources/application.yml
- Correct @Param annotation to allow param input in studies Swagger UI
- Correct some incorrect response code (space char in code)
- Add 2 authentication method (bearer, Oauth2) to allow authentication in studies Swagger UI
- Access studies Swagger UI : https://shanoir-qualif.irisa.fr/shanoir-ng/studies/swagger-ui/index.html
- Authenticate with OAuth2 method (click on "Authorize :lock:" button)
> ![image](https://github.com/fli-iam/shanoir-ng/assets/59697998/69e9ccd1-0f56-46f8-9a74-8b64129b2c7c)
(keep client_secret empty)
- Test some endpoints
- Authenticate with Bearer method (click on "Authorize :lock:" button)
Use token from browser console
- Test some endpoints
=> [swagger] Fix studies swagger UI

shanoir-ng-front/src/app/studies/study/study.component.html
How to test:
Check that there is not a "Display as public" field in the **Files** tab
=> shanoir-issue#2274: remove field

docker-compose-dev.yml, shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/messaging/SubjectStudyUpdateBroadcastService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RelatedDatasetServiceImpl.java
How to test:
Create two new studies
Import preclinical datasets in one
From solr, select the imported datasets and click "copy to study", select the other study
Once the copy is done, the new study should have datasets and a similar tree structure (subject, exam, dataset acquisition, dataset)
Before fix:
No subject in 'subject' tab, datasets appearing in solr but this tree:
=> Subjects not copied during copy of preclinical datasets

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/DatasetProcessingServiceImpl.java
Closes #2300 
How to test:
- Delete a processed dataset
=> Shanoir issue#2300 delete processed dataset

shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
How to test:
- Select a dataset in solr, which have an acquisition with multiple datasets (important)
- Click on re-apply a study card
- Apply a study card WITH some rules (important)
--> No error
Closes #2326
=> #2326-re-apply-study-card

shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/ExaminationData.java
Correction of a regression due to the switch from Examination object to ExaminationData object in CheckQuality()
=> set studyId to examinationData before checkQuality()

shanoir-ng-front/src/app/import/pre-clinical-context/pre-clinical-context.component.ts
=> shanoir-issue#2346: show study card selection on brucker import

shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.css, shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.html, shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.ts, shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts
Adds the possibility to choose the outcome structure of a download :
=> Add download options : folder structure

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
How to test:
Search for a serie with a special character in its name (write ' ° ' in the solr search bar)
Open it in OHIF viewer
The name should be displayed correctly
=> shanoir-issue#2366: special char in ohif

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resource/ProcessingResourceRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resource/ProcessingResourceService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resource/ProcessingResourceServiceImpl.java
- Remove cascade delete from dataset to processing
- Remove procsessing when deleting dataset
Closes #2300 
How to test:
- Delete a processed dataset (or a processing) from a processing with multiple processed datasets (example: ct-tiqua on neurinfo qualif)
=> #2300 - delete processing bug

docker-compose/Dockerfile, shanoir-ng-back/pom.xml, shanoir-ng-keycloak-auth/pom.xml, shanoir-uploader/pom.xml
- Upgrade maven dependencies
@michaelkain everything seems to work properly. I'm testing on qualif.
I tested shanoir-uploader too.
=> #2371-keycloak-upgrade-25.0.4

shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts, shanoir-ng-front/src/app/studies/study/study.component.html, shanoir-ng-front/src/app/studies/study/study.component.ts
How to test:
Open a study
The "download study" button is removed
=> shanoir-issue#2397: remove 'download study' button

shanoir-ng-front/src/app/studies/study/tree.service.ts
fix https://github.com/fli-iam/shanoir-ng/issues/2396
=> fix processed datasets in tree

docker-compose/database/db-changes/datasets/0054_study_users_update.sql, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/StudyServiceImpl.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java, shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQStudiesService.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java, shanoir-ng-study-rights/src/main/java/org/shanoir/ng/study/rights/ampq/RabbitMqStudyUserService.java, shanoir-ng-study-rights/src/main/java/org/shanoir/ng/study/rights/ampq/StudyUserUpdateService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQUserService.java
This may be a hotfix.
How to test:
- Add a new user on a study, this user can now create an examination on the study.
I also corrected some little bug I encountered on the way.
-validate() that fails
- exam deletion from a study
=> #2422-study_user_bug

shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition-list/dataset-acquisition-list.component.ts, shanoir-ng-front/src/app/datasets/dataset-list/dataset-list.component.ts, shanoir-ng-front/src/app/datasets/dataset-processing-list/dataset-processing-list.component.ts, shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts, shanoir-ng-front/src/app/preclinical/anesthetics/examination_anesthetic/list/examinationAnesthetic-list.component.ts, shanoir-ng-front/src/app/preclinical/examination/list/animal-examination-list.component.ts, shanoir-ng-front/src/app/preclinical/pathologies/subjectPathology/list/subjectPathology-list.component.ts, shanoir-ng-front/src/app/preclinical/therapies/subjectTherapy/list/subjectTherapy-list.component.ts, shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts, shanoir-ng-front/src/app/solr/solr.search.component.ts, shanoir-ng-front/src/app/studies/study-list/study-list.component.ts, shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.ts, shanoir-ng-front/src/app/subjects/subject-list/subject-list.component.ts, shanoir-ng-front/src/app/users/user-list/user-list.component.ts, shanoir-ng-front/src/app/vip/execution-monitorings/execution-monitorings.component.ts
Fix date problems in lists by letting the table component handle all cases.
=> remove dates renderers, use the on built in table component

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
How to test:
- Delete an exam
-> No error
=> #2432-correct-delete-exam-bug

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/CreateStatisticsService.java, shanoir-ng-datasets/src/main/resources/logback-spring.xml, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiSecurityTest.java, shanoir-ng-front/src/app/async-tasks/async-tasks.component.html, shanoir-ng-front/src/app/async-tasks/async-tasks.component.ts, shanoir-ng-front/src/app/async-tasks/status/task-status.component.html, shanoir-ng-front/src/app/async-tasks/status/task-status.component.ts, shanoir-ng-front/src/app/async-tasks/task.model.ts, shanoir-ng-front/src/app/async-tasks/task.service.ts, shanoir-ng-front/src/app/datasets/download-statistics/download-statistics.component.ts, shanoir-ng-front/src/app/datasets/shared/dataset.service.ts, shanoir-ng-front/src/app/shared/components/table/table.component.html, shanoir-ng-front/src/app/shared/components/table/table.component.ts, shanoir-ng-front/src/app/shared/notifications/notifications.service.ts, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.css, shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html, shanoir-ng-front/src/app/users/shanoir-event/shanoir-event.model.ts, shanoir-ng-front/src/app/utils/app.utils.ts, shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEventType.java, shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
How to test:
As an admin, open "Download statistics" page
A new job has appeared:
A link to download the statistics is available, after 6 hours, the statistics file will be deleted
Click the link to download the file:
=> shanoir-issue#2188: prepare stats + download from task page

shanoir-ng-front/src/app/welcome/welcome.component.html
=> shanoir-issue#2425: change 'public' to 'shared'

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java, shanoir-ng-study-rights/src/main/java/org/shanoir/ng/study/rights/ampq/RabbitMqStudyUserService.java, shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java, shanoir-ng-users/src/test/java/org/shanoir/ng/accessrequest/AccessRequestApiControllerTest.java
Closes #2398 
How to test:
- Create an access request as a new user
- Connect a shanoir admin
- Access to the access request from the study detail -> no bug
- Accept the request -> The request actually disappear.
=> shanoir#2398-access-request-admin-bug better display access request for for shanoir admin.

shanoir-ng-front/src/app/app.component.css, shanoir-ng-front/src/app/app.component.html, shanoir-ng-front/src/app/app.module.ts, shanoir-ng-front/src/app/datasets/shared/dataset-processing.dto.ts, shanoir-ng-front/src/app/shared/components/dropdown-menu/dropdown-menu.component.ts, shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts, shanoir-ng-front/src/app/shared/components/tree/tree-node.component.css, shanoir-ng-front/src/app/shared/components/tree/tree-node.component.html, shanoir-ng-front/src/app/shared/components/tree/tree-node.component.ts, shanoir-ng-front/src/app/shared/double-awesome/double-awesome.component.css, shanoir-ng-front/src/app/shared/double-awesome/double-awesome.component.html, shanoir-ng-front/src/app/shared/double-awesome/double-awesome.component.ts, shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts, shanoir-ng-front/src/app/studies/study-history/study-history.component.ts, shanoir-ng-front/src/app/studies/study/study-tree.component.css, shanoir-ng-front/src/app/studies/study/study-tree.component.html, shanoir-ng-front/src/app/studies/study/study-tree.component.ts, shanoir-ng-front/src/app/studies/study/tree.service.ts, shanoir-ng-front/src/app/studies/tree/study-node.component.css, shanoir-ng-front/src/app/studies/tree/study-node.component.html, shanoir-ng-front/src/app/studies/tree/study-node.component.ts, shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts, shanoir-ng-front/src/app/tree/tree.model.ts
see https://github.com/fli-iam/shanoir-ng/issues/2392
List of demands : 
* slider because ican subjects too long [OK]
* buttons visible [OK]
* open by default [OK]
* text filter [OK]
* unselect all ? [OK]
* refresh tree when deleting from a list (i.e. acquisition) [OK]
=> Tree updates

.github/workflows/docker.yml
=> CI: use docker-compose-dev.yml for building the images

.github/workflows/docker.yml
#2464 was broken (the doc examples are misleading)
=> CI: fix workflow syntax

shanoir-ng-front/src/app/studies/tree/study-node.component.ts, shanoir-ng-front/src/app/subjects/subject/subject.component.html, shanoir-ng-front/src/app/subjects/subject/subject.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
@pierrehenri-dauvergne I thin you can remove your PR :)
=> Shanoir issue#2475 subject name

.github/workflows/docker.yml, shanoir-ng-front/src/app/studies/tree/study-node.component.ts, shanoir-ng-front/src/app/subjects/subject/subject.component.html, shanoir-ng-front/src/app/subjects/subject/subject.component.ts, shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
Just to add the subject's name check
=> develop to master

shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
How to test:
Import data in new examination
Try to delete examination
Should work
=> shanoir-issue#2492: fix id -> examinationId

bootstrap.sh
- Update bootstrap.sh with adapted docker-compose file
=> #2364 - github packages - 2 bootstrap.sh

shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
How to test:
- Import a new subject from shanoir uploader -> subject can actually be created.
- Import a subject from interface with spaces -> Subject is well trimmed.
=> Shanoir hotfix#2497 subject name bug

shanoir-ng-import/pom.xml
Removed 2 dependencies in import pom
If it builds its ok right @michaelkain ?
=> remove apache poi dependency

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-front/src/app/import/processed-dataset-clinical-context/processed-dataset-clinical-context.component.css, shanoir-ng-front/src/app/import/processed-dataset-clinical-context/processed-dataset-clinical-context.component.html, shanoir-ng-front/src/app/import/processed-dataset-clinical-context/processed-dataset-clinical-context.component.ts
Closes #2476 
How to test:
Make an "import from processed dataset"
When creating the processing, no error.
=> #2476 - create processing error

shanoir-ng-back/pom.xml
All tests ran properly in local.
=> #2527 : Springboot 3.2.2 -> 3.4.0

shanoir-ng-front/src/app/shared/mass-download/download-setup-alt/download-setup-alt.component.css, shanoir-ng-front/src/app/shared/mass-download/download-setup-alt/download-setup-alt.component.html, shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts
* disabled download button on firefox when loading info
see https://github.com/fli-iam/shanoir-ng/issues/2573
=> disabled download button on firefox when loading info

.github/workflows/docker.yml
This Pull Request answers issue #2597 . The github bake action used was updated to v5
=> [BF]: updated bake-action github action used

shanoir-ng-anonymization/pom.xml, shanoir-ng-datasets/pom.xml, shanoir-ng-exchange/pom.xml, shanoir-ng-front/pom.xml, shanoir-ng-import/pom.xml, shanoir-ng-ms-common/pom.xml, shanoir-ng-nifti-conversion/pom.xml, shanoir-ng-parent/pom.xml, shanoir-ng-preclinical/pom.xml, shanoir-ng-studies/pom.xml, shanoir-ng-study-rights/pom.xml, shanoir-ng-users/pom.xml, shanoir-uploader/pom.xml
I hope there is no miss understanding between spring version and module version (they were all 3.2.2, I guessed this wasn't a coincidence but a link with the spring version)
=> 2527 : springboot 3.2.2 -> 3.4.0 for all ms

shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/ExaminationDatasetAcquisitionDecorator.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/ExaminationDatasetAcquisitionMapper.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java
Potential solution for https://github.com/fli-iam/shanoir-ng/issues/2622
successfully tested on ofsep-qualif with subject, that has 7 exams and therefore the most exams
=> Hot fix to avoid huge sql related to copies (where source_id = ?)

docker-compose/database/3_add_statistics_procedure.sql, docker-compose/database/db-changes/datasets/0056_add_statistics_procedure.sql
How to test:
Make the same stat export before and after deploying this PR
Before: the job takes too long, at some point if you refresh the page you can see "inactivity timeout, there must has been" (message is cut)
After: the job works properly
=> shanoir-issue#2635: fix get size procedure

shanoir-ng-front/src/app/quality-control/quality-control.component.html
Apply QC on study is disabled:
=> shanoir-issue#2659: disable 'apply qc' button in quality tab

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java, shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java
Hi @pierrehenri-dauvergne, I tried to optimize things for the issue:
https://github.com/fli-iam/shanoir-ng/issues/2658
I introduced a limit for mass deletion to 500 datasets.
Could you please test it on ofsep-qualif? I tested locally.
=> Try to optimize delete dataset

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Serie.java, shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java, shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/query/SerieTreeNode.java
potential fix for #2678 and now display seriesNumber in tree view of ShUp
=> ShUp: optimize for seriesNumber ordering in tree

shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyLightDTO.java, shanoir-ng-studies/src/main/java/org/shanoir/ng/study/repository/StudyRepository.java
How to test:
Open the study-list, no error
Make a multiple examination import (see [#2728](https://github.com/fli-iam/shanoir-ng/pull/2728) )
=> shanoir-issue#2738: add JsonIgnore on profile field

shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/execution/service/ExecutionServiceImpl.java, shanoir-ng-datasets/src/main/resources/application.yml
Tested in remote. "-" to "" replacement will be changed to "-" to "_" in the future, when VIP is ready.
=> 2717 : Modification of Shanoir prefix for VIP API HTTP requests/responses

shanoir-ng-front/src/app/shared/mass-download/download-setup-alt/download-setup-alt.component.ts, shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.ts
Tested in qualif. Check the issue for more details
=> #2790 : download pop up correction

shanoir-ng-import/src/main/java/org/shanoir/ng/importer/DatasetsCreatorService.java
Optimization for issue: https://github.com/fli-iam/shanoir-ng/issues/2641
Unknown, how a serieUID can enter the DICOM study with a timestamp,
that is before the acquisition actually started. So, more info for next time,
but not a fix, as not a problem on Shanoir side.
=> MS Datasets: duplicate serieID folder: log seriesDescription

shanoir-ng-front/src/app/study-cards/quality-card/quality-card.component.css, shanoir-ng-front/src/app/study-cards/quality-card/quality-card.component.html
see https://github.com/fli-iam/shanoir-ng/issues/2636
just adds a warning message if you check "auto check at import"
=> warning message for auto import in quality card

shanoir-ng-front/src/app/studies/study/study.component.ts
How to test:
Create a study, select "DISABLED" for study card policy, create a study
--> The pop-up asking if you want to create a study card doesn't show up
Do the same but this time, select "MANDATORY" (it's the default value) and create a study
--> The pop-up shows up
=> shanoir-issue#2849: add condition for creating a sc after create study

shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/execution/service/ExecutionTrackingServiceImpl.java
Length check for substring added
=> #2753 : tiny correction for dataset names written in VIP execs trackng file

shanoir-ng-front/src/app/centers/center/center.component.html, shanoir-ng-front/src/app/centers/center/center.component.ts, shanoir-ng-front/src/app/shared/validators/shanoir-validators.ts
PLEASE CARE : this PR includes https://github.com/fli-iam/shanoir-ng/pull/2886
=>  #2881 : correcting some field checks for center form creation/edition 

shanoir-ng-front/src/app/shared/validators/shanoir-validators.ts
Tiny commit : 
The proposition is to create a shanoir class for generic validators (including angular native validators, they had to be copied)
=> #NOISSUE : shared shanoir-validators creation

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/ProcessingDownloaderServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/utils/DatasetFileUtils.java
Currently in test on qualif : 
Hi ! Here are the 2 commits to merge into master for being able to process both SIMS and PMAP pipelines :
- 2890 : The longer commit between both, but the more important. Relative to that [not merged PR](https://github.com/fli-iam/shanoir-ng/pull/2923) and that [merged PR](https://github.com/fli-iam/shanoir-ng/pull/2891)
- 2904 :  The shorter commit between both, and the less important. Relative to that [not merged PR](https://github.com/fli-iam/shanoir-ng/pull/2905)
=> Vip features to merge

shanoir-ng-front/src/app/shared/side-menu/side-menu.component.css
fix https://github.com/fli-iam/shanoir-ng/issues/2906
tasks close button are nor floating anymore
=> fix task floating close button

shanoir-ng-front/src/app/shared/components/entity/entity-list.browser.component.abstract.ts, shanoir-ng-front/src/app/shared/components/table/table.component.ts, shanoir-ng-front/src/app/studies/study-list/study-list.component.ts, shanoir-ng-front/src/app/users/user-list/user-list.component.ts
fix https://github.com/fli-iam/shanoir-ng/issues/2836#issuecomment-3163930320
(= study name now appears in user list csv export)
also fixes study list table export
=> wait all async fields in csv export

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
- Avoids heap space error
- Stop loading file entirely in memory and switch to streaming
TESTING
but new code provides less memory consumption, 944Mb to 1.3Gb during and after the import
=> Fix Github issue #3036

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
Reverts fli-iam/shanoir-ng#3076
=> Revert "[BUGFIX]: Download processed images in DICOM format."

shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java, shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
HOTFIX for PR #3076 that was reverted by PR #3085 
Resolves issue #3071
=> [HOTFIX]: Download processed images in DICOM format.
