- shanoir-ng-front/src/app/coils/coil-list/coil-list.component.html
- shanoir-ng-front/src/app/datasets/dataset-list/dataset-list.component.ts
- shanoir-ng-front/src/app/shared/checkbox/checkbox.component.css
- shanoir-ng-front/src/app/shared/checkbox/checkbox.component.html
- shanoir-ng-front/src/app/shared/checkbox/checkbox.component.ts
- shanoir-ng-front/src/app/shared/components/table/table.component.css
- shanoir-ng-front/src/app/shared/components/table/table.component.html
- shanoir-ng-front/src/app/shared/components/table/table.component.ts
- shanoir-ng-front/src/app/shared/components/tree/tree-node.component.ts
**Usage :**
Add ` [selectionAllowed]="true"` to the `<shanoir-table>` tag and then catch selected rows with the `(selectionChange)` event.
**Exemple :** 
* in html
```
<shanoir-table #table
[getPage]="getPage.bind(this)" 
[columnDefs]="columnDefs" 
[customActionDefs]="customActionDefs" 
(rowClick)="onRowClick($event)"
[browserSearch]="false"
[selectionAllowed]="true"
(selectionChange)="onSelectedChange($event)">
</shanoir-table>
```
* in component
```
onSelectedChange(selected: Dataset[]) {
console.log(selected);
}
```
**Warning :**
When clicking 'select all' on a backend paging entities table, a request will fetch every single entity ( getAll() ). Else, how could we know what is selected? We probably will set a limit.
> selectable rows in tables

- shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/repository/SubjectRepository.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java
- shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/SubjectApiSecurityTest.java
- shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/SubjectServiceSecurityTest.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpener.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpenerNG.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListener.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListenerNG.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListener.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListenerNG.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/AuthenticationConfigurationState.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/gui/ImportDialog.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/HttpService.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClientNG.java
* Big feature extension: automatic token refresh with Keycloak, so ShUp can be used and kept open all time now
Especially important for testing and usage
* Bug fix for: create RelSubjectStudy if existing subject in other study (e.g. situation of patient moves) for REST connection
with Shanoir-NG
* Bug fix for: Caused by: javax.persistence.NonUniqueResultException: result returns more than one elements
at org.shanoir.ng.subject.service.SubjectServiceImpl.findSubjectFromCenterCode(SubjectServiceImpl.java:196)
at org.shanoir.ng.subject.service.SubjectServiceImpl.createAutoIncrement(SubjectServiceImpl.java:114)
> ShanoirUploader v6.0.2: extensions for sh-ng

- docker-compose/datasets/Dockerfile
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/controler/DatasetAcquisitionApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DatasetAcquisitionContext.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomPersisterService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/DatasetStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/dataset/MrDatasetStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/DatasetAcquisitionStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/MrDatasetAcquisitionStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetexpression/DatasetExpressionContext.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetexpression/DatasetExpressionStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetexpression/DicomDatasetExpressionStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/protocol/MrProtocolStrategy.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/CStoreDicomService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/DicomServiceApi.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/StowRsDicomService.java
- shanoir-ng-datasets/src/main/resources/application.yml
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/utils/StreamGobbler.java
* Integrates c-store and wado-uri into ms datasets to assure backward compatibility with
dcm4chee2 (for production Neurinfo we agreed with the admin to keep for the moment
the current dcm4chee2 to reduce change overhead for installation of new version).
The flag „ dcm4chee-arc.dicom.web“ can be used to switch between c-store+wado-uri
and stowrs+wadors.
* By default now dicom images are sent to the pacs with c-store as tests showed, that
160 images with c-store require 3 secs and 160 images with stowrs require 4 secs in average
* Integrates a new exception handling and stops the „silent“ exceptions in ms datasets
* Installs dcm4che-5.21.0 into ms datasets (Dockerfile), to be used on the command line
* Fixes a major bug in DatasetAcquisitionApiController.java (setImportJob on …
> MS Datasets: c-store and wado-uri introduced + bug fixes

- docker-compose/migration_scripts/Neurinfo/1_users_migration.py
here is a PR which:
- reverts b400e112931 (as discussed last week)
- but restores the `ALTER TABLE` statements for the date fields in the users table (the qualif users ms is currently not running because these changes are missing)
Also I added several automated mysqldump commands in the deployment script to dump the db schemas. This will allow easy comparisons.
| file |  description |
| ----- | ------------------ |
| /var/log/dk/qualif/dbdump-pre-migration.sql | all databases before migration (as created by the ms) |
| /var/log/dk/qualif/dbdump-post-migration.sql | all databases after migration |
| /var/log/dk/qualif/dbdump-prod-studies.sql  | production users db |
| /var/log/dk/qualif/dbdump-prod-users.sql | production studies db |
> New db fixes

- docker-compose/users/entrypoint
Typically a manually-installed certicate is expected to be signed
by a well-known CA (so there is no need to add it to the custom
keystore).
> do not require the custom keystore if the cert is not autogenerated

- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
- shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/SubjectApiSecurityTest.java
Instead of fetch all subjects - subject_study - study_user to filter
for the rights, start with user - user_study - subject_study, do it
the other way round. In the ideal: the front would only ask for the
subjects required.
> Quick fix for Qualif: examinations loading time GitHub issue #377:

- docker-compose.yml
Fix asked by Anthony:
1) use /var/solr as standard folder within named volume, to avoid outside usage,
as in any case (see doc) Solr will put files into /var/solr
2) log level of Solr set to SEVERE to reduce log pollution in prod env
> 2 Fixes for Solr

- docker-compose/import/Dockerfile
alternative to #514 to avoid storing dcm2nii config files into an external volume (because `/tmp` needs to be mounted)
> Shanoir issue#511

- shanoir-ng-front/src/version.ts
- match the current tag format (NG_vxxxx)
- always display the git commit (longSemver=true)
- restore the '-dirty' mark (showed when the git repo is not clean)
> fix the version displayed on the front

- docker-compose.yml
I updated DockerHub image for dicomifier.ws to tag 1.0 so that it is updated with the new image i loaded.
=> This new image uses 0.0.0.0 instead of 127.0.0.1 to be seen from shanoir-network.
> Shanoir issue#563 - Dicomifier not working

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrSequenceVariant.java
- shanoir-ng-front/src/app/import/query-pacs/query-pacs.component.html
- shanoir-ng-front/src/app/import/select-series/select-series.component.html
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
Prod: import from pacs: use exam date to sort request answer after Pacs query #540
- PatientRootQuery now considers dicom study date and study description as additional criteria
- Dicom study level ordered by study date (-> exam in Shanoir) old to newest
- Dicom tree: displays now the date of the Dicom study (-> exam in Shanoir)
- Wrong date display of Dicom study fixed
> Fix for GitHub issues: #540 (Pacs import)+#561: import data issue

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApi.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/ExaminationDatasetAcquisitionDTO.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/ExaminationDatasetAcquisitionDecorator.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionMapperTest.java
- shanoir-ng-front/src/app/datasets/download/dataset-download.component.html
- shanoir-ng-front/src/app/datasets/download/dataset-download.component.ts
- shanoir-ng-front/src/app/datasets/tree/dataset-node.component.html
- shanoir-ng-front/src/app/examinations/shared/examination.pipe.ts
- shanoir-ng-front/src/app/examinations/tree/examination-node.component.html
- shanoir-ng-front/src/app/shared/components/dropdown-menu/menu-item/menu-item.component.html
- shanoir-ng-front/src/app/shared/components/dropdown-menu/menu-item/menu-item.component.ts
- shanoir-ng-front/src/app/study-cards/tree/study-card-node.component.ts
- shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts
see https://github.com/fli-iam/shanoir-ng/issues/646
* / false behind each dataset (serie dicom), e.g. 3dTof 1 / false ... :ok: 
* View studycard detail from study tree => error ... :ok:  
* 3D T2 FS () behind each exam (actually behind dataset acquisitions) ... :ok:
* As expert, from examination no access to dataset list in tree ... :ok: 
*  issue: icon in menu for examination is not the same as in tree ... :ok: 
* When downloading from dataset detail in study-tree => download launched twice. Due to element cliocked in ? ... :ok: 
* user type User, all rights in study, study details (studyId 178) - click on 001 patient and try to download dicom of first dataset -> error (first mail) ... :ok: 
* user type User, all rights in study, study details (studyId 178) - selected 3 datasets of …
> Tree fixes

- shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.ts
I think the dicom archive that Elise was importing contains wrong string values for the phantoms sex. It causes the backend to bug. Now that we check the value the bug should disappear.
Not easy to test.
> fix error with subject creation see #630

- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
- Avoid NPE when converting tag value into double[] to allow import
> Shanoir-issue#670 Correct import - data with no image orientation

- docker-compose/database/3_add_statistics_procedure.sql
to take into account rows which do not have pseudonymus_hash_values.
basically it now uses a left join instead of an inner join for the pseudonymus_hash_values table:
from studies.subject as sb
left join studies.pseudonymus_hash_values as pseud on (pseud.id = sb.pseudonymus_hash_values_id)
inner join studies.study as st
...
> fix statistics export procedure 

- shanoir-ng-front/src/app/solr/solr.search.component.ts
- Only add special char for the moment (prepare for later update => Fix
schema not using SolrConfig.schemaCreationSupport, add center and add
"all" field to search on all fields.)
> Shanoir-issue#574 (actually #674)  special character in search bar

- docker-compose/nginx/entrypoint
replace app.css to styles.*.css in docker-compose/nginx/entrypoint si…nce angular 10 does not generate app.css but styles.*.css
> Fix app.css styles in entrypoint

- .env
- docker-compose.yml
- docker-compose/nginx/entrypoint
- shanoir-ng-front/src/assets/css/common.css
- utils/entrypoint_common
(replaces SHANOIR_COLORS)
Suggestion: how about
- showing the instance name and colors in the keycloak login page
- showing the instance name in the html `<title>`
> add SHANOIR_INSTANCE_NAME/SHANOIR_INSTANCE_COLOR

- shanoir-ng-users/src/main/java/org/shanoir/ng/email/EmailServiceImpl.java
- shanoir-ng-users/src/main/resources/templates/notifyStudyAdminDataImported.html
@michaelkain I corrected it rapidly if we want to merge it before midday.
Check that the examination ID appears in the generated mail:
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head></head>
<body>
<p>Dear <span>Julien</span> <span>Louis</span>, <br />
User <span>jlouis</span> imported data to study <span>DemoStudy</span>.</p>
<p>Study card: <span>elleafait</span><br />
Subject: <span>TestMail</span><br />
<a href="https://shanoir-ng-nginx/shanoir-ng/examination/details/22">Examination 22</a> <br />
Examination Date: <span>2010-03-04</span></p>
<p> Datasets: <br />
<ul>
<li><a href="https://shanoir-ng-nginx/shanoir-ng/dataset/details/167">tse_vfl_WIP607</a></li>
<li><a href="https://shanoir-ng-nginx/shanoir-ng/dataset/details/168">tse_vfl_WIP607</a></li>
<li><a …
> Shanoir-issue#930 Import email - add examination ID

- db-changes/datasets/27062021_EEG_rank_db_changes.sql
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
EEG acquisition rank is set to 0 by default
> Shanoir-issue#976 EEG acquisition rank display

- shanoir-ng-users/src/main/java/org/shanoir/ng/extensionrequest/controller/ExtensionRequestApiController.java
How to test
- Grab an activated user
- Try to ask extension request => fail
- Update this user to set the "first_expiration_notification_sent" to true in DB
- Re ask for an account extension
- The account extension is well sent.
> Shanoir-issue#923 Extension request can be asked after first mail

- docker-compose/import/Dockerfile
Hot to test:
- Deploy
- Import data with a study card with dcm2niix
- Check that the conversion is correctly done
- You can also connect to the shanoir-ng-import microservice and make
- -dcm2niix --version
to check the software version.
> Shanoir-issue#920 update dcm2niix version to 2021-03-17

- shanoir-ng-front/src/app/shared/components/papaya/papaya.component.ts
Closes #868 
Closes #873 
Do not consider nifti transforms when displaying in papaya
To test this, I got the dicom from Alban study, can eventually be sent.
> Shanoir-issue#868 papaya issues

- shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.html
- shanoir-ng-front/src/app/studies/study/study.component.ts
Import non MR -> No study card warning display
Edit an existing study with study card -> Do not display the warning.
Closes #893
> shanoir-issue#893 Update study-card warning (update study + import MR)

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
- Avoid exception by initializing the MessageConverter at the Context
creation in WadoDownloaderService
This is considered a hotfix, that has to be merged in develop then.
How to test:
- Download multiple datasets as Dicom
Closes #1121
> Shanoir-issue#1121 ConcurrentModificationException while downloading DS

- shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java
When creating/editing a study as an expert, all subjects are proposed.
Display only subjects the expert 'can see' in other studies. (can be discussed) 
Closes #1134
> Shanoir-issue#1134 Expert user - study edit subjects available

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/exporter/service/BIDSServiceImpl.java
Clear datasets log file.
When BIDS create iterate over the datasets, it copies the files from nifti file to BIDS folder.
When some of these file already exists, at the moment, an error is set and the logs are flooded.
With this correction, we override the file (which is quite logic to keep the last imported file)
How to test:
- Import some dicom with a given study, subject, examination
- Re-import the exact same file with same study, same subject, same examination -> The logs are no more flooded and the BIDS folder is up to date.
Closes #1120
> shanoir-issue#1120 Clear BIDS logs - Override file creation

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
- shanoir-ng-front/src/app/examinations/examination/examination.component.ts
- shanoir-ng-front/src/app/subjects/subject/subject.component.html
- shanoir-ng-front/src/app/subjects/subject/subject.component.ts
How to test:
- Before launching test, import data, create a subject with a name with a slash.
--> Data are not accessible anymore
- After deploy
--> Dataset download is now possible
--> It is now impossible to create a new subject with a name with a '/' in it. (and other specific chars)
Closes #1070
> Shanoir issue#1070 subject name limitation + download

- docker-compose/database/db-changes/users/0001_user_expiration_notification.sql
- shanoir-ng-users/src/main/java/org/shanoir/ng/user/model/User.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java
When updating a user and changing its expiration date, expiration mail triggers were never reset. So changed users (26 on prod) would never receive these expiration messages.
Update database so that all users can now receive correctly expiration notifications.
Now when an expiration date is changed, we reset these triggers.
How to test:
- Force a user in DB with the triggers to true as if mails had already been sent:
`update users set first_expiration_notification_sent = true, second_expiration_notification_sent = true where id = 1;`
- Update this user by changing its expiration date
- Now these two boolean are reset to false.
Closes #1118
> Shanoir issue#1118 Expiration date update resets expiration notification

- shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
Shanoir events are now stored for 1 year.
Closes #1156
> Shanoir-issue#1156 Delete events older than 1 year.

- shanoir-ng-front/package-lock.json
When building the production images this file is updated (to add these missing deps), which makes changes in git's working tree, which makes git-describe add the `-dirty` suffix to the version number.
> add missing dependencies

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
- Wait 30sc for nifti reconversion.
How to test:
Deploy on qualif
Detail of 405591 -> reconvert nifti with mcverter
-> The dataset is well downloaded in nifti
Closes #1129
> Shanoir-issue#1129 RabbitMQ timeout for nifti reconversion

- shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/RabbitMQSubjectService.java
Closes #1146 
This method was lacking a "transactionnal" tag to allow a session.
> Shanoir-issue#1146 Error while importing data from OFSEP uploader

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/SolrRepositoryImpl.java
Any spaces in Solr free search where escaped and it made the search return no results. This is fixed here.
Now there is a question. Currently, a free search with several words separated by spaces search for datasets that have at least one of those keywords in any of it's field. 
* use case : studyA studyB gives datasets from studyA and datasets from studyB
But would it be better if it gave datasets that contains every term ?
* use case : 3d t1 subjectA , here the user wants 3d t1 from the sujectA, not every dataset from the database that mention '3d'
For instance in amazon it's a mix of both logic : at top of the results it's the second solution, then there are suggestions that ignore one or more terms.
In my opinion we should go for the second solution. Let's discuss it at the daily.
> fix solr bug (can't use several keywords)

- docker-compose/nginx/shanoir.template.conf
This new setup blocks all locations by default and only allows the
minimal set needed by the users.
> reduce the exposed surface of the keycloak UI/API

- utils/oneshot
Keycloak does not appreciate being killed with SIGPIPE. This makes it crash with a segfault when runing a migration task (eg: `SHANOIR_MIGRATION=init`)
```
------------------- sending SIGTERM -------------------
/usr/bin/oneshot: line 65:    23 Segmentation fault      exec "$@" > "$fifo1" 2>&1
------------------- terminated (exit 0) -------------------
```
with this change, it only receives a SIGTERM, and terminates cleanly:
```
------------------- sending SIGTERM -------------------
*** JBossAS process (447) received TERM signal ***
10:20:12,656 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0050: Keycloak 12.0.3 (WildFly Core 13.0.3.Final) stopped in 174ms
*** JBossAS process (447) received TERM signal ***
------------------- terminated (exit 0) -------------------
```
> oneshot: ensure child process is not killed with SIGPIPE

- shanoir-ng-front/src/app/datasets/shared/dataset.service.ts
- shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts
Closes #1296 
It was all in the front from the beginning...
When clicking on the button, the download method was executed twice, exactly at the same time, leading to an error (FileAlreadyExistException AND FileNotFoundException).
> shanoir-issue#1296 Allow massive download

- shanoir-ng-front/src/app/preclinical/animalSubject/edit/animalSubject-form.component.ts
- shanoir-ng-front/src/app/preclinical/pathologies/pathologyModel/edit/pathologyModel-form.component.html
- shanoir-ng-front/src/app/preclinical/pathologies/subjectPathology/list/subjectPathology-list.component.ts
- shanoir-ng-front/src/app/preclinical/shared/subjectEntity-list-input.abstract.ts
- shanoir-ng-front/src/app/preclinical/therapies/subjectTherapy/list/subjectTherapy-list.component.ts
Closes #1294
How to test:
- Create a new preclinical subject (either import brucker data or directly go to preclinical-subject/create)
- Add a new pathology and therapy
- They are correctly displayed in the table
> Shanoir issue#1294 Add subject therapy/pathology during subject creation

- docker-compose.yml
- docker-compose/nginx/shanoir.template.conf
- shanoir-ng-datasets/src/main/resources/application.yml
- shanoir-ng-import/src/main/resources/application.yml
- shanoir-ng-preclinical/src/main/resources/application.yml
- shanoir-ng-studies/src/main/resources/application.yml
- shanoir-ng-users/src/main/resources/application.yml
- utils/entrypoint_common
- application.yml of all 5 microservices cleaned from old spring properties
- preclinical microservice changed to port 9905, to unify port schema for all ms
- utils/entrypoint_common adapted to spring boot 2.6.6 and sql.init.mode change
> spring-boot-2.6.6: final adaptations

- docker-compose/datasets/Dockerfile
- docker-compose/import/Dockerfile
- docker-compose/preclinical/Dockerfile
- docker-compose/studies/Dockerfile
- docker-compose/users/Dockerfile
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/ImportJob.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/utils/ShanoirExec.java
- shanoir-ng-import/src/main/resources/logback-spring.xml
- shanoir-imports.log introduced, slight modification on shanoir-events.log format
- one line of CSV style log, per import started: evaluate especially the percentage of DICOM Enhanced used during the imports
- shanoir-ng-import.log optimised: nifti conversion removed + warnings reduced
- better debug with remote application: change in all Dockerfile (for dev only)
> New imports.log

- shanoir-ng-front/src/app/datasets/dataset-list/dataset-list.component.ts
Closes #1344 
Datasets cannot be sorted by subject name or study name anymore.
> shanoir-issue#1344 disallow dataset table sorting: study / subject

- docker-compose.yml
Note that the postgresql upgrade is not automatic (need to make a full dump and import of the base). In the dev environment you can just destroy the relevant volumes.
> upgrade to dcm4chee 5.27.0

- .github/workflows/maven.yml
- docker-compose/database/check_migration_names.py
The "check migration names" stage in the ci pipeline fails to detect existing migrations in the master branch. They appear as `(none)` in https://github.com/fli-iam/shanoir-ng/actions/runs/3046116136/jobs/4908518031
With proper detection this script would have caught the bugs that had to be fixed in ca84e9502b and d25400f693.
Note: #1407 has to be merged before this PR (otherwise this fix will make it fail the test)
> fix the detection of existing migrations

- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpener.java
Closes #1412 
How to test:
- Create an equipment with no serial number
- Create a study card with this equipment
- Try to upload data on this study using shanoir uploader
--> There should be no error.
> shanoir-issue#1412 Shanoir-uploader - bug when equip number null

- shanoir-ng-import/src/main/resources/logback-spring.xml
When an error happens during import in ImporterManagerService, it is now displayed.
Closes #1476
> #1476 display import log in file and console

- shanoir-ng-front/src/app/import/basic-clinical-context/basic-clinical-context.component.ts
Closes #1524 
How to test:
- Import not preclinical data
- The examination now appears in examination list
Scripts to go on Neurinfo
`UPDATE examination SET preclinical = false where id > 19964;`
(I checked, no preclinical datasets were imported in this timeframe)
OFSEP:
`UPDATE examination SET preclinical = false where id > 39439;`
(I checked, no preclinical datasets imported ever on ofsep server)
> #1524 preclinical exams bug - not preclinical by default

- docker-compose/nginx/shanoir.template.conf
Hi, my local tests work:
- https://shanoir-ng-nginx goes to /shanoir-ng/welcome
- when I click access, I go to the login page, when I cancel I come back
> Fix for problem of PH: by default go to public catalog

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
- shanoir-ng-datasets/src/main/resources/application.yml
This makes dcm4chee return the DICOM objects as they were received and stored (it disables attribute coercion and merge of information)
> use the AS_RECEIVED aet by default in Q/R operations

- docker-compose/database/shanoir-entrypoint.sh
As of mysql/mysql-server:5.7.34 `/mysql-init-complete` was moved into the `/var/lib/mysql-files/` directory.
> Fix mysql container hanging at startup

- shanoir-ng-front/src/app/studies/study/study.component.html
- shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/user/model/User.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java
Closes #1544 
Hi @michaelkain, I don't really get how we arrived to this.
- Users impossible deletion was quite logic -> They are still linked to one ore more access request. I updated the logic so that, when a user is deleted, associated access requests are deleted.
For the second point, it's quite misterious, we have user with "account_request_on_demand" set to NULL, as they should be set to either "true" (non existing user) or "false" (existing user).
For the already existing user, I can imagine that the "on demand" could be set to null, and I added a check, but for non existing user, I cannot understand how we arrived in that state..
I'll check a little bit further..
Jean-Côme
> #1544 - access request - allow user deletion & access request

- shanoir-ng-front/src/app/shared/select/select.component.ts
fix https://github.com/fli-iam/shanoir-ng/issues/1599
* the bug was with firefox and the new angular version
* the actual reason of the bug was a bad implementation of a compare function
> fix select box scroll going backwards (issue #1599)

- docker-compose/keycloak/Dockerfile
- docker-compose/keycloak/entrypoint
8df648cc1610 removed code which was not actually dead.
A small list of keycloak variables have to be set at runtime *and* at buildtime. If not, then the quarkus image is dynamically rebuilt at each startup, which currently cause a 3-minute delay.
> fix keycloak build-time config

- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFromCsvRunner.java
- Add study ID to identifier using CSV import to avoid problems with subject in multiple studies
Close #1609 
How to test:
- Import data with CSV with shanoir-uploader in a study A, with a subject already existing in study B (the user should not have any rights in this other study)
--> The subject is well created and importer
> #1609-uploader-subject-identifier

- shanoir-ng-front/src/app/datasets/download/dataset-download.component.html
- shanoir-ng-front/src/app/datasets/shared/dataset.service.ts
- shanoir-ng-front/src/app/examinations/examination/examination.component.html
- shanoir-ng-front/src/app/examinations/shared/examination.service.ts
- shanoir-ng-front/src/app/examinations/tree/examination-node.component.html
- shanoir-ng-front/src/app/home/challenge/challenge-block.component.html
- shanoir-ng-front/src/app/shared/components/loading-bar/loading-bar.component.html
- shanoir-ng-front/src/app/shared/components/loading-bar/loading-bar.component.ts
- shanoir-ng-front/src/app/solr/solr.search.component.html
- shanoir-ng-front/src/app/studies/shared/study.service.ts
- shanoir-ng-front/src/app/studies/study/study.component.html
- Do not display progress anymore for download
- Display size downloaded
- still display progress for uploads
Closes #1621 
How to test:
Download data from
- solr detail
- examination detail
- Study detail (dataset + associated files (DUA potentially)
- dataset detail
--> We display the size
Upload data during import
--> We display the upload bar correctly
> #1621 - download bar to NaN following zipInputFile download

- shanoir-ng-front/src/app/studies/studyuser/studyuser-list.component.ts
- shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApi.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserService.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java
- shanoir-ng-users/src/test/java/org/shanoir/ng/accessrequest/AccessRequestApiControllerTest.java
- Add specific method for invitation to get user by username
Closes #1668 
How to test:
- Connect as an expert
- Go to an administrable study detail
- Edit it to add a member using its username (and not mail)
--> The user is well added
> #1668 - invitation as expert bug

- shanoir-ng-import/src/main/resources/logback-spring.xml
- Remove faulty line that was removing import logs.
Closes #1676 
@michaelkain that was my bad.
How to test:
- Make an import
- Logs are now in import.log and not anywhere else
> #1676 import logs not working anymore

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/Operation.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/condition/StudyCardCondition.java
- shanoir-ng-front/src/app/study-cards/shared/study-card.model.ts
- shanoir-ng-front/src/app/study-cards/study-card-rules/condition/condition.component.ts
- Add "does not contain" rule in study cards
Closes #1685 
How to test:
- Create a study card with a specific "does not contain" rule
- Import data with and without this rule beeing respected
- Check that the output corresponds
> #1685-does-not-contain-study-card

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/field/DatasetAcquisitionMetadataField.java
Quick fix for the unparsable studycard coil id reported by Elise. Here we just ignore the string values so no Coil will be set in updated metadata in those cases.
> coil-body-parse-quickfix

- shanoir-ng-front/src/app/shared/select/select.component.css
- shanoir-ng-front/src/app/shared/select/select.component.html
- shanoir-ng-front/src/app/shared/select/select.component.ts
- shanoir-ng-front/src/app/studies/study/study.component.css
- shanoir-ng-front/src/app/studies/study/study.component.html
- shanoir-ng-front/src/app/studies/study/study.component.ts
- shanoir-ng-front/src/assets/css/common.css
Sorry I'm reverting the previous PR because 
* it broke the studycard/qualitycard rule edition, shrinking select boxes
* there can't be specific code mentioning "center" in an ultra generic component like select-box
* there was already a method in select.component.ts named computeMinWidth() that was supposed to compute the minimum width of the list
* the actual problem was that when opening the study page, the center tab is display:none which interfere with the width calculation
> Revert + Fix long center name

- docker-compose/database/db-changes/datasets/0027_downloadable_datasets.sql
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
How to test:
- Before deploying, import some data (or force creation date)
- Download old data = OK
- Download data with acquisition creation_date  between 17 to 28 june -> Download fails.
> Security fix after Rennes's hack

- shanoir-ng-front/src/app/solr/solr.search.component.ts
When clicking "Run a process" in solr view, check if user has the correct rights on selected datasets.
If not, an error dialog will be displayed.
See https://github.com/fli-iam/shanoir-ng/wiki/Roles-and-rights-specification#synthesis-table
- Admin can run a process
- User can not run a process
- Expert with CAN_ADMIN rights on all selected datasets can run a process
> [fli-iam#1663] Check rights when running pipeline on datasets

- shanoir-ng-front/src/app/preclinical/animalSubject/edit/animalSubject-form.component.html
- shanoir-ng-front/src/app/preclinical/animalSubject/edit/animalSubject-form.component.ts
- shanoir-ng-front/src/app/preclinical/animalSubject/list/animalSubject-list.component.ts
- shanoir-ng-preclinical/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQPreclinicalService.java
- shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/controller/AnimalSubjectApi.java
- shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/controller/AnimalSubjectApiController.java
- shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectApiControllerTest.java
Deletion of an animal subject is now only possible via API through the deletion of its linked subject.
The animal subject deletion is triggered through a RabbitMQ event.
This allow the check of the user rights on the subject, and the deletion of linked objects on subject side (e.g. examinations)
Solve #1816 and #1802
How to test :
- Delete an animal subject through the list or the detail view
- Check that the list is well updated, and that the linked objects are deleted also
> [fli-iam#1816][fli-iam#1802] Delete animal subject only through subject

- shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
- shanoir-ng-front/src/app/shared/components/table/browser-paging.model.ts
- shanoir-ng-front/src/app/shared/components/table/table.component.ts
- shanoir-ng-front/src/app/studies/shared/study.service.ts
- shanoir-ng-front/src/app/studies/study-list/study-list.component.html
- shanoir-ng-front/src/app/studies/study-list/study-list.component.ts
- shanoir-ng-front/src/app/studies/study/study.component.ts
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
In study list :
- Sorting by "storage volume" is now correct
- Sorting on "storage volume" is disabled while fetching
- ~Storage volumes are fetched only for studies loaded in the current page~ (not possible due to sorting)
Correct https://github.com/fli-iam/shanoir-ng/issues/1868
How to test :
- Display study list as admin (so all the studies will be loaded, it will take some time)
- Order by "storage volume", asc & desc (must be disabled while fetching)
- Display study details
> [fli-iam#1846] Correct order by numeric value in lists

- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApi.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApiController.java
How to test :
Send a big examination (grouped by examination) through the `test-shanoir/0.1` VIP pipeline
The creation of the processed dataset should not fail.
> [fli-iam#1866] Upload of VIP result data fail when content too long

- docker-compose/keycloak/cfg/shanoir-ng-realm.json
- shanoir-ng-front/src/app/shared/side-menu/side-menu.component.ts
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dua/DataUserAgreement.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dua/DataUserAgreementRepository.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dua/DataUserAgreementService.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
- Allow study deletion with a DUA
- Archive existing DUAs
- Keep trace of DUA signing
- Re-ask DUA signing when updating DUA
- Show notifications correctly
Closes #1897
Closes #1896 
Closes #1873 
Closes #1764 
How to test:
- Create a new study as expert
- Add another user (not admin)
--> The user has access to the study
- Add a DUA to this study
--> The other has no access anymore, but has a notif to sign it
- Sign the DUA as the other user
--> The user has access to the study
- Update this DUA 
--> The other has no access anymore, but has a notif to sign it
- Delete the DUA
--> The user has access to the study
The check in microservice
- DB -> We kept the trace of every user signing
- /var/studies-data/study-XX -> We archived all the DUAs
> #1896 dua corrections

- docker-compose/database/3_add_statistics_procedure.sql
The DICOM size is the sum of all `dataset_expressions` (with a `dataset_expression_format` equals to 6) linked to the dataset.
> add dicom_size_mo column in export statistics procedure

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
- Allow deletion of acquisition
- Allow deletion of dataset correctly
Closes #1922 
How to test:
- Select acquisition with MR data
- Delete acquisition
- Acquisition was well deleted
--> You can check on pacs (either try to retrieve dicom from qualif with dataset_file path or locally on PACS interface)
- delete a dataset
--> You can check on pacs (either try to retrieve dicom from qualif with dataset_file path or locally on PACS interface)
local pacs: http://localhost:8081/dcm4chee-arc/ui2/study/study
Otherwise, CURL from dataset microservice (if possible)
> #1922-acquisition-deletion

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
- shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.html
- shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.ts
- shanoir-ng-front/src/app/datasets/dataset/dataset.component.ts
- [fli-iam/shanoir-ng/issues/1921] After deleting a dataset, the user is now redirected to https://shanoir-qualif.irisa.fr/shanoir-ng/solr-search
- [fli-iam/shanoir-ng/issues/1918] `Explored entity`, `Cardinality of relAted subjects`, `Processed Type` fields are now displayed in lower case & capitals in dataset view mode
- [fli-iam/shanoir-ng/issues/1917] User now cannot change the modality of a dataset in edit mode
-  [fli-iam/shanoir-ng/issues/1916] User now cannot change the subject of a dataset in edit mode
> Fix some small issues on dataset view

- .github/workflows/docker.yml
Hi @michaelkain,
I've been able to successfully manually run this workflow on my fork (https://github.com/youennmerel/shanoir-ng) by putting mock value (`v1.0`) in the $TAG env variable.
This seems to (finally) work fine :
> ![image](https://github.com/fli-iam/shanoir-ng/assets/59697998/95cf3fc7-55c7-4ce5-aba0-ab206c9e38fc)
> ![image](https://github.com/fli-iam/shanoir-ng/assets/59697998/88d4ea47-2bef-43c4-8d70-5ea61596dde4)
The only uncertainty now is that `${{ github.ref }}` will give us the right $TAG value on triggered run, but it seems to be clearly the good variable to use : https://github.com/orgs/community/discussions/26686#discussioncomment-3396593
> [CI] Push docker image with version in tag

- .github/workflows/docker.yml
Hi @michaelkain,
So sorry, but i had a doubt about the trigger condition for the docker workflow :
- This mean that the workflow will be also be triggered when pushing on master, so this will create a docker tag `master` :
```
branches:
- 'master'
```
I've removed this condition to keep only the `tags` one.
- This regex won't work with `NG_vx.x.x` tags
```
tags:
- 'v*'
```
> [CI] Docker push : change trigger condition

- docker-compose.yml
- docker-compose/keycloak/Dockerfile
This is just to match the configuration we have in production. Especially we need to set the KC_LOG env variable at build time so that quarkus is not rebuilt at every startup
(see commit 98c52cc04bfe71b2da60b520df89c8a1b3a41590)
> output keycloak logs to an external volume

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
- shanoir-ng-datasets/src/main/resources/application.yml
- shanoir-ng-import/src/main/resources/application.yml
- shanoir-ng-preclinical/src/main/resources/application.yml
- shanoir-ng-studies/src/main/resources/application.yml
- shanoir-ng-users/src/main/resources/application.yml
This PR correct the Swagger viewers.
Documentation is now directly displayed when accessing Swagger UI.
(Already corrected links in Wiki)
(URLs for local instance)
- https://shanoir-ng-nginx/shanoir-ng/datasets/swagger-ui/index.html
- https://shanoir-ng-nginx/shanoir-ng/import/swagger-ui/index.html
- https://shanoir-ng-nginx/shanoir-ng/preclinical/swagger-ui/index.html
- https://shanoir-ng-nginx/shanoir-ng/studies/swagger-ui/index.html
> ![image](https://github.com/fli-iam/shanoir-ng/assets/59697998/60bc9cfc-b6eb-4b71-bf41-9f5965afbbd2)
> Correct swagger UI

- shanoir-ng-front/src/app/shared/utils/handle-error.service.ts
fix https://github.com/fli-iam/shanoir-ng/issues/1909
the error message appears when the jobs/tasks permanent connection is interrupted more than 45s (you can pause the user container)
> hide "reconnecting" error message

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
Hotfix to correct problem for PRIMUS
How to test:
- Import a processed dataset on a dataset A
- Download dataset A as dicom
-> The dataset is downloaded as nifti
> Shanoir issue#2032 hotfix processed datasets download

- shanoir-ng-front/src/app/subjects/subject/subject.component.html
- shanoir-ng-front/src/app/subjects/subject/subject.component.ts
How to test:
Go to subject
Click 'new'
Fill the mandatory forms (first name, last name, common name, date of birth): 'create' button is disabled
Pick a study: 'create' button is enabled
Remove the study: 'create' button is disabled and a message says "study is required"
Now, you can't create a subject without linking it to a study
> shanoir-issue#2069: during subject creation, make it mandatory to pick a study

- .github/dependabot.yml
Hi @michael,
It seems it's possible to use dependabot to update git submodules :
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
- https://nicholaswilde.io/libbash/installation/#update
With this custom config, dependabot should check weekly if there is a new commit in https://github.com/Inria-Empenn/shanoir_downloader/ and submit a pull request as for other dependencies
> Manage git submodules update with dependabot

- shanoir-ng-front/src/app/shared/console/console.component.css
Slightly shift the 'widden console' arrow so that it's not overlapped by the scroll bar on linux systems
> shanoir-issue#2064: scroll and deploy-console button overlap in fedora

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
How to test: good question.
- Stop pacs microservice before the import ?
- The error isn't clear -> It says "could not delete from pacs" which is not quite logic. The error should change.
> #2097 - error during import leads to deletion and error swallow

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
How to test:
Create a study
Import dataset in it
Go to pacs and reject series
Go to examination page and delete the created exam
Before:
Error is thrown and examination is not properly deleted
Now:
No error is thrown and examination is deleted
Tested on: local and qualif
> shanoir-issue#2087: do not throw exception when pacs can't delete

- shanoir-ng-front/package.json
since shanoir is open source, i don't see any reason not to build the source maps
> build the source maps by default

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/controller/DatasetPropertyApi.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/controller/DatasetPropertyApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/model/DatasetPropertyDTO.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/model/DatasetPropertyMapper.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/repository/DatasetPropertyRepository.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/service/DatasetPropertyService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/service/DatasetPropertyServiceImpl.java
Add 2 endpoints in dataset MS to query dataset properties
- GET /properties/dataset/{datasetId}
- check user CAN_SEE_ALL right on given dataset
- GET /properties/processing/{processingId}
- keep properties for which user has CAN_SEE_ALL right on dataset
- Check datasets swagger doc
- Check APIs with cURL (copy a query example "as cURL" in browser console and adapt it)
- Check different user rights
> [fli-iam#2192] New properties API endpoints

- docker-compose/README.md
- docker-compose/database/Dockerfile
- docker-compose/datasets/Dockerfile
- docker-compose/import/Dockerfile
- docker-compose/keycloak-database/Dockerfile
- docker-compose/nginx/Dockerfile
- docker-compose/nifti-conversion/Dockerfile
- docker-compose/preclinical/Dockerfile
- docker-compose/solr/Dockerfile
- docker-compose/studies/Dockerfile
- docker-compose/users/Dockerfile
Here is a series of optimisations to reduce the build time and image sizes thanks to various buildkit features. I documented them in `docker-compose/README.md`
With these optimisations, building the images with *docker buildx bake* on the github runners roughly takes: 
- 10 minutes for the initial build
```
468.1s  [nifti-conversion]
142.3s  [datasets]
84.2s  [keycloak]
81.3s  [preclinical]
59.0s  [studies]
51.6s  [import]
48.2s  [users]
38.3s  [keycloak-database]
35.3s  [solr]
8.9s  [nginx]
2.0s  [database]
```
- 50 seconds for the next builds (minimum time when the dockerfile are unchanged)
```
33.4s  [nifti-conversion]
31.2s  [keycloak]
30.2s  [preclinical]
23.0s  [datasets]
20.9s  [studies]
18.3s  [users]
5.9s  [import]
3.6s  [solr]
1.7s  [nginx]
0.8s  [database]
0.0s …
```
> Dockerfile optimisations

- shanoir-ng-front/src/app/studies/study/study.component.html
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
How to test:
As an expert, create a study
Make sure to have the admin rights
Edit study
Check the "challenge" checkbox and save
Before this PR, we had to be an admin to make it a challenge, now an expert can do it.
> shanoir-issue#2228: remove condition 'is admin' to make a study a challenge

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/Cardinality.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/DicomTagType.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/VM.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/condition/StudyCardDICOMConditionOnDatasets.java
in study cards & quality cards conditions, Slice Thickness (and others) dicom tag should not be <FloatArray> but just <Float>.
The problem was that the dicom Value Representation (VR) named Decimal String (DS) can be arrays or single values so I changed the conversion rules.
> dicom vr ds & di better vm management (slice thickness is float array bug)

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
- Correct "Dataset cannot be null here" error when updating dataset tags
**Use datasets swagger**, or :
This cURL example set study tags 8, 9, 10 to dataset 2
(Change `[TOKEN]` before executing, copy it from browser console)
``` shell
curl --insecure -X 'PUT' 'https://shanoir-ng-nginx/shanoir-ng/datasets/datasets/2/tags' \
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Authorization: Bearer [TOKEN]' \
-H 'Content-Type: application/json' \
-H 'Connection: keep-alive' \
-H 'Sec-Fetch-Dest: empty' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Sec-Fetch-Site: same-origin' \
-d '[
8, 9, 10
]'
```
- Check that …
> Correct right check on update dataset tags endpoint

- docker-compose/database/oneshot-updates/tag_ofsep_organs.sql
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/model/Study.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/model/StudyTag.java
- Optimize tags indexation when updating a study
- Make Solr indexation async when :
- applying study cards
- updating subject
- updating study
- Correct `volume.organ` dataset tags creation
- Deploy on OFSEP qualif
- Execute `tag_ofsep_organs.sql`
- Reindex Solr
- Check that study update time is reasonable
- Check that processings are linked to datasets of the same study
- Check that created datasets tags are linked to tags of the same study 
- Check that update of subject is OK
- Check that reapplying study cards is OK
> [fli-iam#2285] Dataset tags optimisations & corrections

- docker-compose/database/db-changes/datasets/0050_examination_update_bug
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
- SQL script to correct updated exams's datasets
- Correct exam update logic
Closes #2293 
How to test:
- Datasets are now downloadable (see [507770](https://shanoir-qualif.irisa.fr/shanoir-ng/dataset/details/507770))
- Update an examination to change subject -> datasets subject are also updated.
> #2293-updated-exam-bug

- docker-compose/database/oneshot-updates/correct_Cohort_VHD_datasets_naming.sql
Datasets from the `Cohorte VHD` study (id 66) were included by mistake in the executions of OSFEP Sequence Identifier pipeline.
This oneshot script correct this by reverting `dataset_metadata.name` to their old value, stored in `dataset_metadat.comment`. Only datasets associated to a dataset_property (i.e. concerned by the executions) will be included in the query.
> Correct Cohorte VHD datasets naming

- docker-compose/Dockerfile
Hi, for 5 microservices, this code brings back the remote debugging option.
Comment back #CMD for the desired microservice
Launch a remote debug in your dev IDE and connect it to the port 991x, x depending on the microservice.
There is no need anymore for the dev-profile, as we run the ms inside docker compose (all in its network) and we "just" run the code in our IDE, as it were inside docker compose, so prod profile is perfect and the most close anyway.
> Remote debugging

- docker-compose/keycloak/entrypoint
we have a rounding issue which makes quarkus fail to detect that the shanoir-ng-keycloak-auth.jar plugin is not modified and rebuild the server at every startup.
> fix keycloak startup time

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomPersisterService.java
Problem: some series, e.g. QSM_3DMULTIGRE_B contain up to 960 DICOM files.
They are organized in multiple directory and packaged by 500 per directory.
MS Datasets searched until this fix the parent directory of the first DICOM file
as reference and sends all containing DICOM files to the server. In the above
case as the DICOM files were distributed over 3 directories only a part of the
files has been send to the PACS. The problem is vendor dependent, as normally
all is structured per serie and concerns only the web import via file, not ShUp,
as in ShUp all DICOM files are queried in only one serie specific folder.
Testing: use serie above and verify, that preview + download work.
> Fix for GitHub issue #2345

- shanoir-ng-front/src/app/shared/components/table/table.component.html
Leaving your mouse over a table's cell displays the full content of the cell:
> shanoir-issue#2333: show full content of cell on mouse over

- bootstrap.sh
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/MrDataset.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/StowRSMultipartRelatedRequestFilter.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomSEGAndSRImporterService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomSRImporterService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetDownloaderServiceTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dicom/web/DICOMJsonApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/exporter/controller/BidsApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardApiControllerTest.java
This code fixes the store-issues with measurements and segmentations, created by ohif-viewer
and index them to Solr. It fixes a rights issue, by attaching it to the original
dataset acquisition, which is the dicom serie, that has been used to create
the measurement, what is correct from the model point of view. So, the user
that has access to the original serie has access to the created measurement
today.
> Index MeasurementDataset to Solr +  fix for bootstrap.sh

- shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts
This msg was not displayed, it was bound to the "chrome" downloading but it actually concerns only the "firefox" one.
closes https://github.com/fli-iam/shanoir-ng/issues/2014
> upstream msg for over limit dl

- shanoir-ng-front/src/app/examinations/examination/examination.component.html
- shanoir-ng-front/src/app/studies/study/study-tree.component.html
- shanoir-ng-front/src/app/studies/study/study-tree.component.ts
- shanoir-ng-front/src/app/tree/tree.model.ts
How to test:
Open a study
Select exams or acquisition and click the "View DICOM" button
This button should be enabled only if: 
- only exams are selected
- acquisitions from a single exam are selected
This is happening because when the viewer is opened, if there are multiple series (acquisition) and studies (exam) selected, the viewer can't know which series belong to which study. In the same way, if there are only series selected, the viewer won't be able to know from which study they are from.
> shanoir-issue#2389: allow 'view dicom' with exams or acquisition from one exam

- shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts
this was resulting in "Cannot read properties of undefined (reading 'updateTree')" when deleting entity from a list
see https://github.com/fli-iam/shanoir-ng/issues/2443
> missing service initialisation

- .github/workflows/docker.yml
the fix in #2461 was incomplete
since our config is no longer in the default 'docker-compose.yml' we need to set our bake files explicitly
https://docs.docker.com/build/bake/reference/
> CI: fix docker bake invocation

- shanoir-ng-front/src/app/studies/tree/study-node.component.ts
- shanoir-ng-front/src/app/subjects/subject/subject.component.html
- shanoir-ng-front/src/app/subjects/subject/subject.component.ts
How to test:
Open subject-list > New
Fill the form (firstname, lastname, date of birth, add a study) and fill the name: if the input after trim (remove starting and ending spaces) is less than 2 char, an error is shown:
Also test during subject creation at import
> shanoir-issue#2475: add new validator to check empty subject name

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionServiceSecurityTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dicom/web/DICOMJsonApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceSecurityTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
- shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts
- shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
- shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html
- shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEvent.java
- shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQStudiesService.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
How to test:
As a user, import DICOM
Create new exam
Wait for import to finish
Delete examination, can be done in multiple ways:
- go to examination page and click the trash icon
- delete the subject in which you imported the data
- delete the study in which you imported the data
A new task is created in the side menu as well as a new job:
> shanoir-issue#2188-2: deletion of exam in async way

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/controler/DatasetProcessingApi.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/controler/DatasetProcessingApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/repository/DatasetProcessingRepository.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/DatasetProcessingServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/ProcessingDownloaderServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/PathApiController.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetDownloaderServiceTest.java
#2488 : API for in/out download from a list of processingIds
This PR  is only relative to the creation of an API, there isn't any Shanoir interface yet, and it's currently specific to CometeMoelle project. Please be aware of the [fli-iam](https://github.com/fli-iam/py_noir/issues/6) feature, which implements a python script for generating API calls to that new API
(Tested in local and in qualif)
> #2488 : API for in/out download from a list of processingIds

- shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
Method for RabbitMQ listener. What is strange is that my preclinical container automatically shutted down when exception was raised, but it wasn't on my old laptop. Really suspicious.
> RabbitMQ_missing_queue: Adding rabbitMQ listener method for animal subject deletion in preclinical ms

- .github/workflows/docker.yml
should fix `ERROR: target nifti-conversion: failed to solve: not found` when building the main branch
> push buildkit cache images in the OCI format

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/EegImporterService.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
- shanoir-ng-import/src/test/java/org/shanoir/ng/importer/ImporterApiControllerTest.java
Import job was creating in dataset module, which was used locally inside it. It had to be created earlier in import module, for being used properly by the module import and rabbitmq which would managed it. I let a if ... else clause, because i'm not sure about the side effect and every use case.
Tested locally and in remote.
> #1874 : import job working properly with eeg (logged as jobs)

- shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventRepository.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
* For events that has a "in progress" status, if no updates after 5 minutes the event is considered "error" and saved as so. The check runs when requesting the list of events so there is no extra db query.
* Also the filtering of the < 7 days is now done by the db query instead of the controller layer
> auto clean of stale events

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
Spring Boot 3.4.0 and Apache Http Client Release 5.4  are probably more restrictive on setContentLength(x smaller than 0), so we set it only in case of existing value to avoid the exception
> Fix for GitHub issue #2606  related to Spring Boot 3.4.0 update

- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomSerieAndInstanceAnalyzer.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListener.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/action/SelectionActionListener.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/DicomServerClient.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/utils/ImportUtils.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/utils/QualityUtils.java
Hi, this PR prepares a new release of ShUp and fixes the following:
- better log in case of ignored dicom instances occur (for debug with CHUGA and ofsep)
- harmonize instances management, in case empty
- continue import in case exception raised during QC (e.g. field corrupted etc.)
- fix: never worked with data from pacs as flag isFromPACS not used to calculate filePath (issue #2616)
> Optimizations on instances == null (ShUp + server) + fix QC from pacs

- shanoir-ng-datasets/src/main/resources/application.yml
- shanoir-ng-import/src/main/resources/application.yml
This PR increases **hikari.maximum-pool-size** on ms import (40 to 50) and ms datasets (60 to 70).
This allows to have more db-connections in the pool for parallel user requests in both microservices.
Our MySQL database, version 5.7, that is behind all 6 microservices has a default
max_connections configuration from **151**.
With this PR, the max_connections are configured and distributed as follows:
- MS Users: default, 10
- MS Studies: default, 10
- MS Import: now 50
- MS Datasets: now 70
- MS Preclinical: default, 10
- MS NIfTI Conversion: 0, as requires NO connection to database
- **SUMMARY: 150** (to relate with the max_numbers supported by MySQL)
> Increase hikari.maximum-pool-size

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetAsyncService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetAsyncServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/DatasetAcquisitionDatasetsMapper.java
- shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java
- shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html
- shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
- shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
[Don't pay attention to my local branch name, I push on the wrong branch]
How to test:
Import a big dataset (the one with id 1334910 on ofsep-qualif is quite big)
Open its details
Delete it
There is a task starting to show its progress. It's now done asynchronously
> shanoir-issue#2658: delete dataset

- shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
In the Serie() constructor, the way how the series number is retrieved has changed.
If not present, it is set to "0", so we need to adapt this as well in the ImagesCreator
AndDicomFileAnalyzerService.java, to retrieve it from the dicom files itself, if not set
by the DICOM server query/retrieve already.
> Fix for change on Serie() constructor: series number from dicom

- shanoir-ng-front/src/app/studies/shared/study.dto.ts
- shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyLightDTO.java
How to test:
Import data > check the "multiple examination import" box
Select a study and a studycard
Select a zip to import, it should be like this:
> TestMET01/M0/ACR_Phantom_t1_se_tra/[data]
> TestMET01/M1/ACR_Phantom_t1_se_tra/[data]
The result gives:
> shanoir-issue#2722: fix study.profile in mass exam import

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/RabbitMQDatasetsService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomSEGAndSRImporterService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/controler/SolrApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrService.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApiController.java
- shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/output/handler/OFSEPSeqIdHandler.java
Instead of update the callers when necessary, I prefered to turn all indexation method (except indexAll(), which is a special case) not blocking by surrounding their lines with a systematic try/catch. Here are some pros and cons :
Pros :
- Won't be blocking at any moment in the future, whatever it's relative to new methods or updated methods.
- Reduce complexity of indexation calls by avoiding exception management
- Not annoying for debug with logs, as we still have the calling stack (not the case for solrUpdate).
Cons : 
- Non specific log message (but not an issue for debug as we still have the calling stack)
- No way to modify indexation failure behaviour (according to me, it's not an issue because indexation is a "secondary" task, but not the core objective of the calling method …
> #2618 : Solr indexation not blocking anymore when failed

- docker-compose/database/db-changes/datasets/0056_add_statistics_procedure.sql
- docker-compose/database/db-changes/datasets/0057_add_statistics_procedure.sql
How to test:
As an admin, open the "download statistics" menu
Fill the "Regular expression filtering the subjects to include" and "Regular expression filtering the subjects to exclude" fields and click the "download statistics" button
Make sure the result file match the form.
The issue comes from the WHERE clause in the procedure which is strange and doesn't use the "subjectNameInRegExp" variable:
From this:
```
WHERE subject.name NOT rlike if(subjectNameOutRegExp IS NULL  OR subjectNameOutRegExp = '', '^\b\B$', subjectNameOutRegExp) 
AND study.name rlike if(studyNameInRegExp IS NULL  OR studyNameInRegExp = '', '.*', studyNameInRegExp)
```
To this:
```
WHERE subject.name rlike if(subjectNameInRegExp IS NULL  OR subjectNameInRegExp = '', '.*', subjectNameInRegExp)
AND subject.name NOT …
```
> shanoir-issue#2750: fix statistics procedure

- docker-compose/Dockerfile
- docker-compose/keycloak/entrypoint
- shanoir-ng-back/pom.xml
- shanoir-ng-front/package-lock.json
- shanoir-ng-front/package.json
- shanoir-ng-front/src/app/shared/keycloak/keycloak.service.ts
- shanoir-ng-front/src/assets/css/login.css
- shanoir-ng-front/src/index.html
- shanoir-ng-front/tsconfig.json
- shanoir-ng-keycloak-auth/pom.xml
- shanoir-ng-users/src/main/java/org/shanoir/ng/ShanoirUsersManagement.java
- shanoir-uploader/pom.xml
https://github.com/fli-iam/shanoir-ng/issues/2696
**front** : instead of importing the keycloak.js (served and host independently by nginx) in index.html, the angular shanoir projet now uses the npm dependency "keycloak-js".  
**back** : update dependencies
(keycloak-admin-client version has to be set manually since the tags no longer stick to the main updates, see https://www.keycloak.org/docs/latest/release_notes/index.html#dedicated-release-cycle-for-the-client-libraries)
**keycloak container** : update version
Just check that you can log to the front and access to data.
> keycloak v26.1.5

- shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpener.java
The issue was due to a refactoring, we were setting compatibleStudyCard back to False in ImportDialogOpener class if the compatible study card was not the last in the study card list.
> bugfix compatible study and study card not selected by default

- .github/workflows/shup_release.yml
This PR corrects some minor mistakes from the previous ShUp release PR.
We get the tag associated with the most recent NG release and not just the latest tag as it was before.
Some tags can be created in advance and cause a mistake in the ShUp version.
> get tag associated with last NG release

- shanoir-uploader/start-shup-linux-mac-java.sh
- shanoir-uploader/start-shup-windows-java.bat
bug fix of .sh and .bat scripts to run as previously (without executables) and injecting app.version into java command for logback to have (avoid the bug of default .su_dev folder created only for su.log file).
> Laurent shup start windows script bugfix

- shanoir-ng-front/src/app/examinations/examination/examination.component.html
- shanoir-ng-front/src/app/examinations/examination/examination.component.ts
Before:
After as mode = view:
Mode = Edit:
How to test:
From an examination's details, click edit and add an extra data (any .zip will do)
Click update
The extra data now appears in the details, click the download button next to it, it works.
Tested only locally
> shanoir-issue#2752: add extra data in examination details

- shanoir-uploader/src/main/java/org/shanoir/uploader/action/FindDicomActionListener.java
- shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/UniquePatientTreeSelectionModel.java
In SHUP, user cannot select multiple DICOM studies or series from different patients.
Multiple selections in the dicom query tree can only be made if they come from the same patient.
To test : 
Query a PACS from ShanoirUploader and try to select multiple nodes from several patients.
> set custom selection model for dicomTree to allow only unique patient selection

- .github/workflows/shup_release.yml
This PR fixes a bug in the release job where we get the latest NG release tag to get the same version number for the SHUP release.
The change from sorting the tags by publication date instead of creation date avoid to get the version of a NG tag created in advance but not yet published.
> sort latest tags by publication date

- shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/output/handler/DefaultHandler.java
Previously, `inputDatasets` referenced the same collection managed by JPA, 
which caused a Hibernate exception when processing the result archive:
`org.springframework.orm.jpa.JpaSystemException: Found shared references to a collection`
Now, we create a new `ArrayList` from `monitoring.getInputDatasets()`, 
ensuring a mutable, independent list for further processing.
Related issue: #3065
> Wrap monitoring input datasets in a new list to avoid shared references (#3065)
